language: node_js
node_js:
  - "8"
  - "10"
  - "12"
script:
  - npm run lint
  - npm run test

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  slack:
    secure: U+RtmtVJEzEoZf+/VVuon9qNC4GXKzXoTqdYThP57ZTzqoDAJDnuZ/qUrMGrMYpYg38ikxtK3qJhBMfffzHXc3KS9hcA7Ay/yPz4QiCBMy3M9EBPWt8iGP6n2T3KUw4WG/hSBUtnJqmwPdzRfVUIqOMgchiN9eWwEbEmSYTvOqA=
