// DO NOT EDIT BY HAND.
// Generated by `packages/node/scripts/generate-intent-commands.ts`.

import { Command, Option } from 'clipanion'
import * as t from 'typanion'

import { robotAudioWaveformInstructionsSchema } from '../../alphalib/types/robots/audio-waveform.ts'
import { robotDocumentAutorotateInstructionsSchema } from '../../alphalib/types/robots/document-autorotate.ts'
import { robotDocumentConvertInstructionsSchema } from '../../alphalib/types/robots/document-convert.ts'
import { robotDocumentOptimizeInstructionsSchema } from '../../alphalib/types/robots/document-optimize.ts'
import { robotDocumentThumbsInstructionsSchema } from '../../alphalib/types/robots/document-thumbs.ts'
import { robotFileCompressInstructionsSchema } from '../../alphalib/types/robots/file-compress.ts'
import { robotFileDecompressInstructionsSchema } from '../../alphalib/types/robots/file-decompress.ts'
import { robotFilePreviewInstructionsSchema } from '../../alphalib/types/robots/file-preview.ts'
import { robotImageBgremoveInstructionsSchema } from '../../alphalib/types/robots/image-bgremove.ts'
import { robotImageGenerateInstructionsSchema } from '../../alphalib/types/robots/image-generate.ts'
import { robotImageOptimizeInstructionsSchema } from '../../alphalib/types/robots/image-optimize.ts'
import { robotImageResizeInstructionsSchema } from '../../alphalib/types/robots/image-resize.ts'
import { robotTextSpeakInstructionsSchema } from '../../alphalib/types/robots/text-speak.ts'
import { robotVideoThumbsInstructionsSchema } from '../../alphalib/types/robots/video-thumbs.ts'
import { parseIntentStep } from '../intentRuntime.ts'
import * as assembliesCommands from './assemblies.ts'
import { AuthenticatedCommand } from './BaseCommand.ts'

export class ImageGenerateCommand extends AuthenticatedCommand {
  static override paths = [['image', 'generate']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate an image from a prompt',
    details:
      'Creates a one-off assembly around `/image/generate` and downloads the result to `--out`.',
    examples: [
      [
        'Generate a PNG image',
        'transloadit image generate --prompt "A red bicycle in a studio" --out bicycle.png',
      ],
      [
        'Pick a model and aspect ratio',
        'transloadit image generate --prompt "An astronaut riding a horse" --model flux-schnell --aspect-ratio 2:3 --out horse.png',
      ],
    ],
  })

  prompt = Option.String('--prompt', {
    description: 'The prompt describing the desired image content.',
    required: true,
  })

  model = Option.String('--model', {
    description: 'The AI model to use for image generation. Defaults to google/nano-banana.',
  })

  format = Option.String('--format', {
    description: 'Format of the generated image.',
  })

  seed = Option.String('--seed', {
    description: 'Seed for the random number generator.',
  })

  aspectRatio = Option.String('--aspect-ratio', {
    description: 'Aspect ratio of the generated image.',
  })

  height = Option.String('--height', {
    description: 'Height of the generated image.',
  })

  width = Option.String('--width', {
    description: 'Width of the generated image.',
  })

  style = Option.String('--style', {
    description: 'Style of the generated image.',
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the generated image to this path',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    const step = parseIntentStep({
      schema: robotImageGenerateInstructionsSchema,
      fixedValues: {
        robot: '/image/generate',
        result: true,
      },
      fieldSpecs: [
        { name: 'prompt', kind: 'string' },
        { name: 'model', kind: 'string' },
        { name: 'format', kind: 'string' },
        { name: 'seed', kind: 'number' },
        { name: 'aspect_ratio', kind: 'string' },
        { name: 'height', kind: 'number' },
        { name: 'width', kind: 'number' },
        { name: 'style', kind: 'string' },
      ],
      rawValues: {
        prompt: this.prompt,
        model: this.model,
        format: this.format,
        seed: this.seed,
        aspect_ratio: this.aspectRatio,
        height: this.height,
        width: this.width,
        style: this.style,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        generated_image: step,
      },
      inputs: [],
      output: this.outputPath,
    })

    return hasFailures ? 1 : undefined
  }
}

export class PreviewGenerateCommand extends AuthenticatedCommand {
  static override paths = [['preview', 'generate']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate a preview image for a remote file URL',
    details:
      'Imports a remote file with `/http/import`, then runs `/file/preview` and downloads the preview to `--out`.',
    examples: [
      [
        'Preview a remote PDF',
        'transloadit preview generate --input https://example.com/file.pdf --width 300 --height 200 --out preview.png',
      ],
      [
        'Pick a format and resize strategy',
        'transloadit preview generate --input https://example.com/file.mp4 --width 640 --height 360 --format jpg --resize-strategy fillcrop --out preview.jpg',
      ],
    ],
  })

  format = Option.String('--format', {
    description:
      'The output format for the generated thumbnail image. If a short video clip is generated using the `clip` strategy, its format is defined by `clip_format`.',
  })

  width = Option.String('--width', {
    description: 'Width of the thumbnail, in pixels.',
  })

  height = Option.String('--height', {
    description: 'Height of the thumbnail, in pixels.',
  })

  resizeStrategy = Option.String('--resize-strategy', {
    description:
      'To achieve the desired dimensions of the preview thumbnail, the <dfn>Robot</dfn> might have to resize the generated image. This happens, for example, when the dimensions of a frame extracted from a video do not match the chosen `width` and `height` parameters.\n\nSee the list of available [resize strategies](/docs/topics/resize-strategies/) for more details.',
  })

  input = Option.String('--input,-i', {
    description: 'Remote URL to preview',
    required: true,
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the generated preview image to this path',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    const previewStep = parseIntentStep({
      schema: robotFilePreviewInstructionsSchema,
      fixedValues: {
        robot: '/file/preview',
        result: true,
      },
      fieldSpecs: [
        { name: 'format', kind: 'string' },
        { name: 'width', kind: 'number' },
        { name: 'height', kind: 'number' },
        { name: 'resize_strategy', kind: 'string' },
      ],
      rawValues: {
        format: this.format,
        width: this.width,
        height: this.height,
        resize_strategy: this.resizeStrategy,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        imported: {
          robot: '/http/import',
          url: this.input,
        },
        preview: {
          ...previewStep,
          use: 'imported',
        },
      },
      inputs: [],
      output: this.outputPath,
    })

    return hasFailures ? 1 : undefined
  }
}

export class ImageRemoveBackgroundCommand extends AuthenticatedCommand {
  static override paths = [['image', 'remove-background']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Remove the background from an image',
    details: 'Runs `/image/bgremove` on each input image and downloads the result to `--out`.',
    examples: [
      [
        'Remove the background from one image',
        'transloadit image remove-background --input portrait.png --out portrait-cutout.png',
      ],
      [
        'Choose the output format',
        'transloadit image remove-background --input portrait.png --format webp --out portrait-cutout.webp',
      ],
    ],
  })

  select = Option.String('--select', {
    description: 'Region to select and keep in the image. The other region is removed.',
  })

  format = Option.String('--format', {
    description: 'Format of the generated image.',
  })

  provider = Option.String('--provider', {
    description: 'Provider to use for removing the background.',
  })

  model = Option.String('--model', {
    description:
      'Provider-specific model to use for removing the background. Mostly intended for testing and evaluation.',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the background-removed image to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('image remove-background requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotImageBgremoveInstructionsSchema,
      fixedValues: {
        robot: '/image/bgremove',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'select', kind: 'string' },
        { name: 'format', kind: 'string' },
        { name: 'provider', kind: 'string' },
        { name: 'model', kind: 'string' },
      ],
      rawValues: {
        select: this.select,
        format: this.format,
        provider: this.provider,
        model: this.model,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        removed_background: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class ImageOptimizeCommand extends AuthenticatedCommand {
  static override paths = [['image', 'optimize']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Optimize image file size',
    details: 'Runs `/image/optimize` on each input image and downloads the result to `--out`.',
    examples: [
      [
        'Optimize a single image',
        'transloadit image optimize --input hero.jpg --out hero-optimized.jpg',
      ],
      [
        'Prioritize compression ratio',
        'transloadit image optimize --input hero.jpg --priority compression-ratio --out hero-optimized.jpg',
      ],
    ],
  })

  priority = Option.String('--priority', {
    description:
      'Provides different algorithms for better or worse compression for your images, but that run slower or faster. The value `"conversion-speed"` will result in an average compression ratio of 18%. `"compression-ratio"` will result in an average compression ratio of 31%.',
  })

  progressive = Option.String('--progressive', {
    description:
      'Interlaces the image if set to `true`, which makes the result image load progressively in browsers. Instead of rendering the image from top to bottom, the browser will first show a low-res blurry version of the image which is then quickly replaced with the actual image as the data arrives. This greatly increases the user experience, but comes at a loss of about 10% of the file size reduction.',
  })

  preserveMetaData = Option.String('--preserve-meta-data', {
    description:
      "Specifies if the image's metadata should be preserved during the optimization, or not. If it is not preserved, the file size is even further reduced. But be aware that this could strip a photographer's copyright information, which for obvious reasons can be frowned upon.",
  })

  fixBreakingImages = Option.String('--fix-breaking-images', {
    description:
      'If set to `true` this parameter tries to fix images that would otherwise make the underlying tool error out and thereby break your <dfn>Assemblies</dfn>. This can sometimes result in a larger file size, though.',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the optimized image to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('image optimize requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotImageOptimizeInstructionsSchema,
      fixedValues: {
        robot: '/image/optimize',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'priority', kind: 'string' },
        { name: 'progressive', kind: 'boolean' },
        { name: 'preserve_meta_data', kind: 'boolean' },
        { name: 'fix_breaking_images', kind: 'boolean' },
      ],
      rawValues: {
        priority: this.priority,
        progressive: this.progressive,
        preserve_meta_data: this.preserveMetaData,
        fix_breaking_images: this.fixBreakingImages,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        optimized: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class ImageResizeCommand extends AuthenticatedCommand {
  static override paths = [['image', 'resize']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Resize an image',
    details: 'Runs `/image/resize` on each input image and downloads the result to `--out`.',
    examples: [
      [
        'Resize an image to 800×600',
        'transloadit image resize --input photo.jpg --width 800 --height 600 --out photo-resized.jpg',
      ],
      [
        'Pad with a transparent background',
        'transloadit image resize --input logo.png --width 512 --height 512 --resize-strategy pad --background none --out logo-square.png',
      ],
    ],
  })

  format = Option.String('--format', {
    description:
      'The output format for the modified image.\n\nSome of the most important available formats are `"jpg"`, `"png"`, `"gif"`, and `"tiff"`. For a complete lists of all formats that we can write to please check [our supported image formats list](/docs/supported-formats/image-formats/).\n\nIf `null` (default), then the input image\'s format will be used as the output format.\n\nIf you wish to convert to `"pdf"`, please consider [🤖/document/convert](/docs/robots/document-convert/) instead.',
  })

  width = Option.String('--width', {
    description:
      'Width of the result in pixels. If not specified, will default to the width of the original.',
  })

  height = Option.String('--height', {
    description:
      'Height of the new image, in pixels. If not specified, will default to the height of the input image.',
  })

  resizeStrategy = Option.String('--resize-strategy', {
    description: 'See the list of available [resize strategies](/docs/topics/resize-strategies/).',
  })

  strip = Option.String('--strip', {
    description:
      'Strips all metadata from the image. This is useful to keep thumbnails as small as possible.',
  })

  background = Option.String('--background', {
    description:
      'Either the hexadecimal code or [name](https://www.imagemagick.org/script/color.php#color_names) of the color used to fill the background (used for the `pad` resize strategy).\n\n**Note:** By default, the background of transparent images is changed to white. To preserve transparency, set `"background"` to `"none"`.',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the resized image to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('image resize requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotImageResizeInstructionsSchema,
      fixedValues: {
        robot: '/image/resize',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'format', kind: 'string' },
        { name: 'width', kind: 'number' },
        { name: 'height', kind: 'number' },
        { name: 'resize_strategy', kind: 'string' },
        { name: 'strip', kind: 'boolean' },
        { name: 'background', kind: 'string' },
      ],
      rawValues: {
        format: this.format,
        width: this.width,
        height: this.height,
        resize_strategy: this.resizeStrategy,
        strip: this.strip,
        background: this.background,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        resized: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class DocumentConvertCommand extends AuthenticatedCommand {
  static override paths = [['document', 'convert']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Convert a document into another format',
    details:
      'Runs `/document/convert` on each input file and downloads the converted result to `--out`.',
    examples: [
      [
        'Convert a document to PDF',
        'transloadit document convert --input proposal.docx --format pdf --out proposal.pdf',
      ],
      [
        'Convert markdown using GitHub-flavored markdown',
        'transloadit document convert --input notes.md --format html --markdown-format gfm --out notes.html',
      ],
    ],
  })

  format = Option.String('--format', {
    description: 'The desired format for document conversion.',
    required: true,
  })

  markdownFormat = Option.String('--markdown-format', {
    description:
      'Markdown can be represented in several [variants](https://www.iana.org/assignments/markdown-variants/markdown-variants.xhtml), so when using this Robot to transform Markdown into HTML please specify which revision is being used.',
  })

  markdownTheme = Option.String('--markdown-theme', {
    description:
      'This parameter overhauls your Markdown files styling based on several canned presets.',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the converted document to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('document convert requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotDocumentConvertInstructionsSchema,
      fixedValues: {
        robot: '/document/convert',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'format', kind: 'string' },
        { name: 'markdown_format', kind: 'string' },
        { name: 'markdown_theme', kind: 'string' },
      ],
      rawValues: {
        format: this.format,
        markdown_format: this.markdownFormat,
        markdown_theme: this.markdownTheme,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        converted: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class DocumentOptimizeCommand extends AuthenticatedCommand {
  static override paths = [['document', 'optimize']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Reduce PDF file size',
    details:
      'Runs `/document/optimize` on each input PDF and downloads the optimized result to `--out`.',
    examples: [
      [
        'Optimize a PDF with the ebook preset',
        'transloadit document optimize --input report.pdf --preset ebook --out report-optimized.pdf',
      ],
      [
        'Override image DPI',
        'transloadit document optimize --input report.pdf --image-dpi 150 --out report-optimized.pdf',
      ],
    ],
  })

  preset = Option.String('--preset', {
    description:
      'The quality preset to use for optimization. Each preset provides a different balance between file size and quality:\n\n- `screen` - Lowest quality, smallest file size. Best for screen viewing only. Images are downsampled to 72 DPI.\n- `ebook` - Good balance of quality and size. Suitable for most purposes. Images are downsampled to 150 DPI.\n- `printer` - High quality suitable for printing. Images are kept at 300 DPI.\n- `prepress` - Highest quality for professional printing. Minimal compression applied.',
  })

  imageDpi = Option.String('--image-dpi', {
    description:
      'Target DPI (dots per inch) for embedded images. When specified, this overrides the DPI setting from the preset.\n\nHigher DPI values result in better image quality but larger file sizes. Lower values produce smaller files but may result in pixelated images when printed.\n\nCommon values:\n- 72 - Screen viewing\n- 150 - eBooks and general documents\n- 300 - Print quality\n- 600 - High-quality print',
  })

  compressFonts = Option.String('--compress-fonts', {
    description:
      'Whether to compress embedded fonts. When enabled, fonts are compressed to reduce file size.',
  })

  subsetFonts = Option.String('--subset-fonts', {
    description:
      "Whether to subset embedded fonts, keeping only the glyphs that are actually used in the document. This can significantly reduce file size for documents that only use a small portion of a font's character set.",
  })

  removeMetadata = Option.String('--remove-metadata', {
    description:
      'Whether to strip document metadata (title, author, keywords, etc.) from the PDF. This can provide a small reduction in file size and may be useful for privacy.',
  })

  linearize = Option.String('--linearize', {
    description:
      'Whether to linearize (optimize for Fast Web View) the output PDF. Linearized PDFs can begin displaying in a browser before they are fully downloaded, improving the user experience for web delivery.',
  })

  compatibility = Option.String('--compatibility', {
    description:
      'The PDF version compatibility level. Lower versions have broader compatibility but fewer features. Higher versions support more advanced features but may not open in older PDF readers.\n\n- `1.4` - Acrobat 5 compatibility, most widely supported\n- `1.5` - Acrobat 6 compatibility\n- `1.6` - Acrobat 7 compatibility\n- `1.7` - Acrobat 8+ compatibility (default)\n- `2.0` - PDF 2.0 standard',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the optimized PDF to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('document optimize requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotDocumentOptimizeInstructionsSchema,
      fixedValues: {
        robot: '/document/optimize',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'preset', kind: 'string' },
        { name: 'image_dpi', kind: 'number' },
        { name: 'compress_fonts', kind: 'boolean' },
        { name: 'subset_fonts', kind: 'boolean' },
        { name: 'remove_metadata', kind: 'boolean' },
        { name: 'linearize', kind: 'boolean' },
        { name: 'compatibility', kind: 'string' },
      ],
      rawValues: {
        preset: this.preset,
        image_dpi: this.imageDpi,
        compress_fonts: this.compressFonts,
        subset_fonts: this.subsetFonts,
        remove_metadata: this.removeMetadata,
        linearize: this.linearize,
        compatibility: this.compatibility,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        optimized: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class DocumentAutoRotateCommand extends AuthenticatedCommand {
  static override paths = [['document', 'auto-rotate']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Correct document page orientation',
    details:
      'Runs `/document/autorotate` on each input file and downloads the corrected document to `--out`.',
    examples: [
      [
        'Auto-rotate a scanned PDF',
        'transloadit document auto-rotate --input scans.pdf --out scans-corrected.pdf',
      ],
    ],
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the auto-rotated document to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('document auto-rotate requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotDocumentAutorotateInstructionsSchema,
      fixedValues: {
        robot: '/document/autorotate',
        result: true,
        use: ':original',
      },
      fieldSpecs: [],
      rawValues: {},
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        autorotated: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class DocumentThumbsCommand extends AuthenticatedCommand {
  static override paths = [['document', 'thumbs']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Render thumbnails from a document',
    details:
      'Runs `/document/thumbs` on each input document and writes the extracted pages or animated GIF to `--out`.',
    examples: [
      [
        'Extract PNG thumbnails from every page',
        'transloadit document thumbs --input brochure.pdf --width 240 --out thumbs/',
      ],
      [
        'Generate an animated GIF preview',
        'transloadit document thumbs --input brochure.pdf --format gif --delay 50 --out brochure.gif',
      ],
    ],
  })

  page = Option.String('--page', {
    description:
      'The PDF page that you want to convert to an image. By default the value is `null` which means that all pages will be converted into images.',
  })

  format = Option.String('--format', {
    description:
      'The format of the extracted image(s).\n\nIf you specify the value `"gif"`, then an animated gif cycling through all pages is created. Please check out [this demo](/demos/document-processing/convert-all-pages-of-a-document-into-an-animated-gif/) to learn more about this.',
  })

  delay = Option.String('--delay', {
    description:
      'If your output format is `"gif"` then this parameter sets the number of 100th seconds to pass before the next frame is shown in the animation. Set this to `100` for example to allow 1 second to pass between the frames of the animated gif.\n\nIf your output format is not `"gif"`, then this parameter does not have any effect.',
  })

  width = Option.String('--width', {
    description:
      'Width of the new image, in pixels. If not specified, will default to the width of the input image',
  })

  height = Option.String('--height', {
    description:
      'Height of the new image, in pixels. If not specified, will default to the height of the input image',
  })

  resizeStrategy = Option.String('--resize-strategy', {
    description: 'One of the [available resize strategies](/docs/topics/resize-strategies/).',
  })

  background = Option.String('--background', {
    description:
      'Either the hexadecimal code or [name](https://www.imagemagick.org/script/color.php#color_names) of the color used to fill the background (only used for the pad resize strategy).\n\nBy default, the background of transparent images is changed to white. For details about how to preserve transparency across all image types, see [this demo](/demos/image-manipulation/properly-preserve-transparency-across-all-image-types/).',
  })

  trimWhitespace = Option.String('--trim-whitespace', {
    description:
      "This determines if additional whitespace around the PDF should first be trimmed away before it is converted to an image. If you set this to `true` only the real PDF page contents will be shown in the image.\n\nIf you need to reflect the PDF's dimensions in your image, it is generally a good idea to set this to `false`.",
  })

  pdfUseCropbox = Option.String('--pdf-use-cropbox', {
    description:
      "Some PDF documents lie about their dimensions. For instance they'll say they are landscape, but when opened in decent Desktop readers, it's really in portrait mode. This can happen if the document has a cropbox defined. When this option is enabled (by default), the cropbox is leading in determining the dimensions of the resulting thumbnails.",
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the extracted document thumbnails to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('document thumbs requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotDocumentThumbsInstructionsSchema,
      fixedValues: {
        robot: '/document/thumbs',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'page', kind: 'number' },
        { name: 'format', kind: 'string' },
        { name: 'delay', kind: 'number' },
        { name: 'width', kind: 'number' },
        { name: 'height', kind: 'number' },
        { name: 'resize_strategy', kind: 'string' },
        { name: 'background', kind: 'string' },
        { name: 'trim_whitespace', kind: 'boolean' },
        { name: 'pdf_use_cropbox', kind: 'boolean' },
      ],
      rawValues: {
        page: this.page,
        format: this.format,
        delay: this.delay,
        width: this.width,
        height: this.height,
        resize_strategy: this.resizeStrategy,
        background: this.background,
        trim_whitespace: this.trimWhitespace,
        pdf_use_cropbox: this.pdfUseCropbox,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        thumbnailed: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class AudioWaveformCommand extends AuthenticatedCommand {
  static override paths = [['audio', 'waveform']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate a waveform image from audio',
    details:
      'Runs `/audio/waveform` on each input audio file and downloads the waveform to `--out`.',
    examples: [
      [
        'Generate a waveform PNG',
        'transloadit audio waveform --input podcast.mp3 --width 1200 --height 300 --out waveform.png',
      ],
      [
        'Generate waveform JSON',
        'transloadit audio waveform --input podcast.mp3 --format json --out waveform.json',
      ],
    ],
  })

  format = Option.String('--format', {
    description:
      'The format of the result file. Can be `"image"` or `"json"`. If `"image"` is supplied, a PNG image will be created, otherwise a JSON file.',
  })

  width = Option.String('--width', {
    description: 'The width of the resulting image if the format `"image"` was selected.',
  })

  height = Option.String('--height', {
    description: 'The height of the resulting image if the format `"image"` was selected.',
  })

  style = Option.String('--style', {
    description:
      'Waveform style version.\n\n- `"v0"`: Legacy waveform generation (default).\n- `"v1"`: Advanced waveform generation with additional parameters.\n\nFor backwards compatibility, numeric values `0`, `1`, `2` are also accepted and mapped to `"v0"` (0) and `"v1"` (1/2).',
    required: true,
  })

  backgroundColor = Option.String('--background-color', {
    description:
      'The background color of the resulting image in the "rrggbbaa" format (red, green, blue, alpha), if the format `"image"` was selected.',
  })

  centerColor = Option.String('--center-color', {
    description:
      'The color used in the center of the gradient. The format is "rrggbbaa" (red, green, blue, alpha).',
  })

  outerColor = Option.String('--outer-color', {
    description:
      'The color used in the outer parts of the gradient. The format is "rrggbbaa" (red, green, blue, alpha).',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the waveform image or JSON data to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('audio waveform requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotAudioWaveformInstructionsSchema,
      fixedValues: {
        robot: '/audio/waveform',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'format', kind: 'string' },
        { name: 'width', kind: 'number' },
        { name: 'height', kind: 'number' },
        { name: 'style', kind: 'string' },
        { name: 'background_color', kind: 'string' },
        { name: 'center_color', kind: 'string' },
        { name: 'outer_color', kind: 'string' },
      ],
      rawValues: {
        format: this.format,
        width: this.width,
        height: this.height,
        style: this.style,
        background_color: this.backgroundColor,
        center_color: this.centerColor,
        outer_color: this.outerColor,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        waveformed: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class TextSpeakCommand extends AuthenticatedCommand {
  static override paths = [['text', 'speak']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Turn a text prompt into spoken audio',
    details: 'Runs `/text/speak` with a prompt and downloads the synthesized audio to `--out`.',
    examples: [
      [
        'Speak a sentence in American English',
        'transloadit text speak --prompt "Hello world" --provider aws --target-language en-US --out hello.mp3',
      ],
      [
        'Use a different voice',
        'transloadit text speak --prompt "Bonjour tout le monde" --provider aws --target-language fr-FR --voice female-2 --out bonjour.mp3',
      ],
    ],
  })

  prompt = Option.String('--prompt', {
    description:
      'Which text to speak. You can also set this to `null` and supply an input text file.',
    required: true,
  })

  provider = Option.String('--provider', {
    description:
      'Which AI provider to leverage.\n\nTransloadit outsources this task and abstracts the interface so you can expect the same data structures, but different latencies and information being returned. Different cloud vendors have different areas they shine in, and we recommend to try out and see what yields the best results for your use case.',
    required: true,
  })

  targetLanguage = Option.String('--target-language', {
    description:
      'The written language of the document. This will also be the language of the spoken text.\n\nThe language should be specified in the [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) format, such as `"en-GB"`, `"de-DE"` or `"fr-FR"`. Please consult the list of supported languages and voices.',
  })

  voice = Option.String('--voice', {
    description:
      'The gender to be used for voice synthesis. Please consult the list of supported languages and voices.',
  })

  ssml = Option.String('--ssml', {
    description:
      'Supply [Speech Synthesis Markup Language](https://en.wikipedia.org/wiki/Speech_Synthesis_Markup_Language) instead of raw text, in order to gain more control over how your text is voiced, including rests and pronounciations.\n\nPlease see the supported syntaxes for [AWS](https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html) and [GCP](https://cloud.google.com/text-to-speech/docs/ssml).',
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the synthesized audio to this path',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    const step = parseIntentStep({
      schema: robotTextSpeakInstructionsSchema,
      fixedValues: {
        robot: '/text/speak',
        result: true,
      },
      fieldSpecs: [
        { name: 'prompt', kind: 'string' },
        { name: 'provider', kind: 'string' },
        { name: 'target_language', kind: 'string' },
        { name: 'voice', kind: 'string' },
        { name: 'ssml', kind: 'boolean' },
      ],
      rawValues: {
        prompt: this.prompt,
        provider: this.provider,
        target_language: this.targetLanguage,
        voice: this.voice,
        ssml: this.ssml,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        synthesized: step,
      },
      inputs: [],
      output: this.outputPath,
    })

    return hasFailures ? 1 : undefined
  }
}

export class VideoThumbsCommand extends AuthenticatedCommand {
  static override paths = [['video', 'thumbs']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Extract thumbnails from a video',
    details: 'Runs `/video/thumbs` on each input video and writes the extracted images to `--out`.',
    examples: [
      [
        'Extract eight thumbnails',
        'transloadit video thumbs --input demo.mp4 --count 8 --out thumbs/',
      ],
      [
        'Resize thumbnails to PNG',
        'transloadit video thumbs --input demo.mp4 --count 5 --format png --width 640 --out thumbs/',
      ],
    ],
  })

  count = Option.String('--count', {
    description:
      'The number of thumbnails to be extracted. As some videos have incorrect durations, the actual number of thumbnails generated may be less in rare cases. The maximum number of thumbnails we currently allow is 999.\n\nThe thumbnails are taken at regular intervals, determined by dividing the video duration by the count. For example, a count of 3 will produce thumbnails at 25%, 50% and 75% through the video.\n\nTo extract thumbnails for specific timestamps, use the `offsets` parameter.',
  })

  format = Option.String('--format', {
    description:
      'The format of the extracted thumbnail. Supported values are `"jpg"`, `"jpeg"` and `"png"`. Even if you specify the format to be `"jpeg"` the resulting thumbnails will have a `"jpg"` file extension.',
  })

  width = Option.String('--width', {
    description:
      'The width of the thumbnail, in pixels. Defaults to the original width of the video.',
  })

  height = Option.String('--height', {
    description:
      'The height of the thumbnail, in pixels. Defaults to the original height of the video.',
  })

  resizeStrategy = Option.String('--resize-strategy', {
    description: 'One of the [available resize strategies](/docs/topics/resize-strategies/).',
  })

  background = Option.String('--background', {
    description:
      'The background color of the resulting thumbnails in the `"rrggbbaa"` format (red, green, blue, alpha) when used with the `"pad"` resize strategy. The default color is black.',
  })

  rotate = Option.String('--rotate', {
    description:
      'Forces the video to be rotated by the specified degree integer. Currently, only multiples of 90 are supported. We automatically correct the orientation of many videos when the orientation is provided by the camera. This option is only useful for videos requiring rotation because it was not detected by the camera.',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the extracted video thumbnails to this path or directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('video thumbs requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotVideoThumbsInstructionsSchema,
      fixedValues: {
        robot: '/video/thumbs',
        result: true,
        use: ':original',
      },
      fieldSpecs: [
        { name: 'count', kind: 'number' },
        { name: 'format', kind: 'string' },
        { name: 'width', kind: 'number' },
        { name: 'height', kind: 'number' },
        { name: 'resize_strategy', kind: 'string' },
        { name: 'background', kind: 'string' },
        { name: 'rotate', kind: 'string' },
      ],
      rawValues: {
        count: this.count,
        format: this.format,
        width: this.width,
        height: this.height,
        resize_strategy: this.resizeStrategy,
        background: this.background,
        rotate: this.rotate,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        thumbnailed: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class VideoEncodeHlsCommand extends AuthenticatedCommand {
  static override paths = [['video', 'encode-hls']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Encode a video into an HLS package',
    details:
      'Runs the `builtin/encode-hls-video@latest` builtin template and downloads the HLS outputs into `--out`.',
    examples: [
      ['Encode a single video', 'transloadit video encode-hls --input input.mp4 --out dist/hls'],
      [
        'Process a directory recursively',
        'transloadit video encode-hls --input videos/ --out dist/hls --recursive',
      ],
    ],
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the HLS outputs into this directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('video encode-hls requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      template: 'builtin/encode-hls-video@latest',
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export class FileCompressCommand extends AuthenticatedCommand {
  static override paths = [['file', 'compress']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Create an archive from one or more files',
    details:
      'Runs `/file/compress` and writes the resulting archive to `--out`. Multiple inputs are bundled into one archive by default.',
    examples: [
      [
        'Create a ZIP archive',
        'transloadit file compress --input assets/ --format zip --out assets.zip',
      ],
      [
        'Create a gzipped tarball',
        'transloadit file compress --input assets/ --format tar --gzip true --out assets.tar.gz',
      ],
    ],
  })

  format = Option.String('--format', {
    description:
      'The format of the archive to be created. Supported values are `"tar"` and `"zip"`.\n\nNote that `"tar"` without setting `gzip` to `true` results in an archive that\'s not compressed in any way.',
  })

  gzip = Option.String('--gzip', {
    description:
      'Determines if the result archive should also be gzipped. Gzip compression is only applied if you use the `"tar"` format.',
  })

  password = Option.String('--password', {
    description:
      'This allows you to encrypt all archive contents with a password and thereby protect it against unauthorized use. To unzip the archive, the user will need to provide the password in a text input field prompt.\n\nThis parameter has no effect if the format parameter is anything other than `"zip"`.',
  })

  compressionLevel = Option.String('--compression-level', {
    description:
      'Determines how fiercely to try to compress the archive. `-0` is compressionless, which is suitable for media that is already compressed. `-1` is fastest with lowest compression. `-9` is slowest with the highest compression.\n\nIf you are using `-0` in combination with the `tar` format with `gzip` enabled, consider setting `gzip: false` instead. This results in a plain Tar archive, meaning it already has no compression.',
  })

  fileLayout = Option.String('--file-layout', {
    description:
      'Determines if the result archive should contain all files in one directory (value for this is `"simple"`) or in subfolders according to the explanation below (value for this is `"advanced"`). The `"relative-path"` option preserves the relative directory structure of the input files.\n\nFiles with same names are numbered in the `"simple"` file layout to avoid naming collisions.',
  })

  archiveName = Option.String('--archive-name', {
    description: 'The name of the archive file to be created (without the file extension).',
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide one or more input files or directories',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the generated archive to this path',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('file compress requires at least one --input')
      return 1
    }

    const step = parseIntentStep({
      schema: robotFileCompressInstructionsSchema,
      fixedValues: {
        robot: '/file/compress',
        result: true,
        use: {
          steps: [':original'],
          bundle_steps: true,
        },
      },
      fieldSpecs: [
        { name: 'format', kind: 'string' },
        { name: 'gzip', kind: 'boolean' },
        { name: 'password', kind: 'string' },
        { name: 'compression_level', kind: 'number' },
        { name: 'file_layout', kind: 'string' },
        { name: 'archive_name', kind: 'string' },
      ],
      rawValues: {
        format: this.format,
        gzip: this.gzip,
        password: this.password,
        compression_level: this.compressionLevel,
        file_layout: this.fileLayout,
        archive_name: this.archiveName,
      },
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        compressed: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: true,
    })

    return hasFailures ? 1 : undefined
  }
}

export class FileDecompressCommand extends AuthenticatedCommand {
  static override paths = [['file', 'decompress']]

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Decompress an archive',
    details:
      'Runs `/file/decompress` on each input archive and writes the extracted files to `--out`.',
    examples: [
      [
        'Decompress a ZIP archive',
        'transloadit file decompress --input assets.zip --out extracted/',
      ],
    ],
  })

  inputs = Option.Array('--input,-i', {
    description: 'Provide an input file or a directory',
  })

  recursive = Option.Boolean('--recursive,-r', false, {
    description: 'Enumerate input directories recursively',
  })

  watch = Option.Boolean('--watch,-w', false, {
    description: 'Watch inputs for changes',
  })

  deleteAfterProcessing = Option.Boolean('--delete-after-processing,-d', false, {
    description: 'Delete input files after they are processed',
  })

  reprocessStale = Option.Boolean('--reprocess-stale', false, {
    description: 'Process inputs even if output is newer',
  })

  singleAssembly = Option.Boolean('--single-assembly', false, {
    description: 'Pass all input files to a single assembly instead of one assembly per file',
  })

  concurrency = Option.String('--concurrency,-c', {
    description: 'Maximum number of concurrent assemblies (default: 5)',
    validator: t.isNumber(),
  })

  outputPath = Option.String('--out,-o', {
    description: 'Write the extracted files to this directory',
    required: true,
  })

  protected async run(): Promise<number | undefined> {
    if ((this.inputs ?? []).length === 0) {
      this.output.error('file decompress requires at least one --input')
      return 1
    }

    if (this.singleAssembly && this.watch) {
      this.output.error('--single-assembly cannot be used with --watch')
      return 1
    }

    const step = parseIntentStep({
      schema: robotFileDecompressInstructionsSchema,
      fixedValues: {
        robot: '/file/decompress',
        result: true,
        use: ':original',
      },
      fieldSpecs: [],
      rawValues: {},
    })

    const { hasFailures } = await assembliesCommands.create(this.output, this.client, {
      stepsData: {
        decompressed: step,
      },
      inputs: this.inputs ?? [],
      output: this.outputPath,
      recursive: this.recursive,
      watch: this.watch,
      del: this.deleteAfterProcessing,
      reprocessStale: this.reprocessStale,
      singleAssembly: this.singleAssembly,
      concurrency: this.concurrency == null ? undefined : Number(this.concurrency),
    })

    return hasFailures ? 1 : undefined
  }
}

export const intentCommands = [
  ImageGenerateCommand,
  PreviewGenerateCommand,
  ImageRemoveBackgroundCommand,
  ImageOptimizeCommand,
  ImageResizeCommand,
  DocumentConvertCommand,
  DocumentOptimizeCommand,
  DocumentAutoRotateCommand,
  DocumentThumbsCommand,
  AudioWaveformCommand,
  TextSpeakCommand,
  VideoThumbsCommand,
  VideoEncodeHlsCommand,
  FileCompressCommand,
  FileDecompressCommand,
] as const
