// DO NOT EDIT BY HAND.
// Generated by `packages/node/scripts/generate-intent-commands.ts`.

import { Command } from 'clipanion'

import { robotAudioWaveformInstructionsSchema } from '../../alphalib/types/robots/audio-waveform.ts'
import { robotDocumentAutorotateInstructionsSchema } from '../../alphalib/types/robots/document-autorotate.ts'
import { robotDocumentConvertInstructionsSchema } from '../../alphalib/types/robots/document-convert.ts'
import { robotDocumentOptimizeInstructionsSchema } from '../../alphalib/types/robots/document-optimize.ts'
import { robotDocumentThumbsInstructionsSchema } from '../../alphalib/types/robots/document-thumbs.ts'
import { robotFileCompressInstructionsSchema } from '../../alphalib/types/robots/file-compress.ts'
import { robotFileDecompressInstructionsSchema } from '../../alphalib/types/robots/file-decompress.ts'
import { robotFilePreviewInstructionsSchema } from '../../alphalib/types/robots/file-preview.ts'
import { robotImageBgremoveInstructionsSchema } from '../../alphalib/types/robots/image-bgremove.ts'
import { robotImageGenerateInstructionsSchema } from '../../alphalib/types/robots/image-generate.ts'
import { robotImageOptimizeInstructionsSchema } from '../../alphalib/types/robots/image-optimize.ts'
import { robotImageResizeInstructionsSchema } from '../../alphalib/types/robots/image-resize.ts'
import { robotTextSpeakInstructionsSchema } from '../../alphalib/types/robots/text-speak.ts'
import { robotVideoThumbsInstructionsSchema } from '../../alphalib/types/robots/video-thumbs.ts'
import {
  createIntentOption,
  GeneratedBundledFileIntentCommand,
  GeneratedNoInputIntentCommand,
  GeneratedStandardFileIntentCommand,
} from '../intentRuntime.ts'

const imageGenerateCommandFields = {
  model: {
    name: 'model',
    kind: 'string',
    propertyName: 'model',
    optionFlags: '--model',
    description: 'The AI model to use for image generation. Defaults to google/nano-banana.',
  },
  prompt: {
    name: 'prompt',
    kind: 'string',
    propertyName: 'prompt',
    optionFlags: '--prompt',
    description: 'The prompt describing the desired image content.',
    required: true,
  },
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description: 'Format of the generated image.',
  },
  seed: {
    name: 'seed',
    kind: 'number',
    propertyName: 'seed',
    optionFlags: '--seed',
    description: 'Seed for the random number generator.',
  },
  aspectRatio: {
    name: 'aspect_ratio',
    kind: 'string',
    propertyName: 'aspectRatio',
    optionFlags: '--aspect-ratio',
    description: 'Aspect ratio of the generated image.',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description: 'Height of the generated image.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description: 'Width of the generated image.',
  },
  style: {
    name: 'style',
    kind: 'string',
    propertyName: 'style',
    optionFlags: '--style',
    description: 'Style of the generated image.',
  },
  numOutputs: {
    name: 'num_outputs',
    kind: 'number',
    propertyName: 'numOutputs',
    optionFlags: '--num-outputs',
    description: 'Number of image variants to generate.',
  },
} as const

const previewGenerateCommandFields = {
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The output format for the generated thumbnail image. If a short video clip is generated using the `clip` strategy, its format is defined by `clip_format`.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description: 'Width of the thumbnail, in pixels.',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description: 'Height of the thumbnail, in pixels.',
  },
  resizeStrategy: {
    name: 'resize_strategy',
    kind: 'string',
    propertyName: 'resizeStrategy',
    optionFlags: '--resize-strategy',
    description:
      'To achieve the desired dimensions of the preview thumbnail, the <dfn>Robot</dfn> might have to resize the generated image. This happens, for example, when the dimensions of a frame extracted from a video do not match the chosen `width` and `height` parameters.\n\nSee the list of available [resize strategies](/docs/topics/resize-strategies/) for more details.',
  },
  background: {
    name: 'background',
    kind: 'string',
    propertyName: 'background',
    optionFlags: '--background',
    description:
      'The hexadecimal code of the color used to fill the background (only used for the pad resize strategy). The format is `#rrggbb[aa]` (red, green, blue, alpha). Use `#00000000` for a transparent padding.',
  },
  strategy: {
    name: 'strategy',
    kind: 'json',
    propertyName: 'strategy',
    optionFlags: '--strategy',
    description:
      'Definition of the thumbnail generation process per file category. The parameter must be an object whose keys can be one of the file categories: `audio`, `video`, `image`, `document`, `archive`, `webpage`, and `unknown`. The corresponding value is an array of strategies for the specific file category. See the above section for a list of all available strategies.\n\nFor each file, the <dfn>Robot</dfn> will attempt to use the first strategy to generate the thumbnail. If this process fails (e.g., because no artwork is available in a video file), the next strategy is attempted. This is repeated until either a thumbnail is generated or the list is exhausted. Selecting the `icon` strategy as the last entry provides a fallback mechanism to ensure that an appropriate strategy is always available.\n\nThe parameter defaults to the following definition:\n\n```json\n{\n  "audio": ["artwork", "waveform", "icon"],\n  "video": ["artwork", "frame", "icon"],\n  "document": ["page", "icon"],\n  "image": ["image", "icon"],\n  "webpage": ["render", "icon"],\n  "archive": ["icon"],\n  "unknown": ["icon"]\n}\n```',
  },
  artworkOuterColor: {
    name: 'artwork_outer_color',
    kind: 'string',
    propertyName: 'artworkOuterColor',
    optionFlags: '--artwork-outer-color',
    description: "The color used in the outer parts of the artwork's gradient.",
  },
  artworkCenterColor: {
    name: 'artwork_center_color',
    kind: 'string',
    propertyName: 'artworkCenterColor',
    optionFlags: '--artwork-center-color',
    description: "The color used in the center of the artwork's gradient.",
  },
  waveformCenterColor: {
    name: 'waveform_center_color',
    kind: 'string',
    propertyName: 'waveformCenterColor',
    optionFlags: '--waveform-center-color',
    description:
      "The color used in the center of the waveform's gradient. The format is `#rrggbb[aa]` (red, green, blue, alpha). Only used if the `waveform` strategy for audio files is applied.",
  },
  waveformOuterColor: {
    name: 'waveform_outer_color',
    kind: 'string',
    propertyName: 'waveformOuterColor',
    optionFlags: '--waveform-outer-color',
    description:
      "The color used in the outer parts of the waveform's gradient. The format is `#rrggbb[aa]` (red, green, blue, alpha). Only used if the `waveform` strategy for audio files is applied.",
  },
  waveformHeight: {
    name: 'waveform_height',
    kind: 'number',
    propertyName: 'waveformHeight',
    optionFlags: '--waveform-height',
    description:
      'Height of the waveform, in pixels. Only used if the `waveform` strategy for audio files is applied. It can be utilized to ensure that the waveform only takes up a section of the preview thumbnail.',
  },
  waveformWidth: {
    name: 'waveform_width',
    kind: 'number',
    propertyName: 'waveformWidth',
    optionFlags: '--waveform-width',
    description:
      'Width of the waveform, in pixels. Only used if the `waveform` strategy for audio files is applied. It can be utilized to ensure that the waveform only takes up a section of the preview thumbnail.',
  },
  iconStyle: {
    name: 'icon_style',
    kind: 'string',
    propertyName: 'iconStyle',
    optionFlags: '--icon-style',
    description:
      'The style of the icon generated if the `icon` strategy is applied. The default style, `with-text`, includes an icon showing the file type and a text box below it, whose content can be controlled by the `icon_text_content` parameter and defaults to the file extension (e.g. MP4, JPEG). The `square` style only includes a square variant of the icon showing the file type. Below are exemplary previews generated for a text file utilizing the different styles:\n\n<br><br> <strong>`with-text` style:</strong> <br>\n![Image with text style]({{site.asset_cdn}}/assets/images/file-preview/icon-with-text.png)\n<br><br> <strong>`square` style:</strong> <br>\n![Image with square style]({{site.asset_cdn}}/assets/images/file-preview/icon-square.png)',
  },
  iconTextColor: {
    name: 'icon_text_color',
    kind: 'string',
    propertyName: 'iconTextColor',
    optionFlags: '--icon-text-color',
    description:
      'The color of the text used in the icon. The format is `#rrggbb[aa]`. Only used if the `icon` strategy is applied.',
  },
  iconTextFont: {
    name: 'icon_text_font',
    kind: 'string',
    propertyName: 'iconTextFont',
    optionFlags: '--icon-text-font',
    description:
      'The font family of the text used in the icon. Only used if the `icon` strategy is applied. [Here](/docs/supported-formats/fonts/) is a list of all supported fonts.',
  },
  iconTextContent: {
    name: 'icon_text_content',
    kind: 'string',
    propertyName: 'iconTextContent',
    optionFlags: '--icon-text-content',
    description:
      'The content of the text box in generated icons. Only used if the `icon_style` parameter is set to `with-text`. The default value, `extension`, adds the file extension (e.g. MP4, JPEG) to the icon. The value `none` can be used to render an empty text box, which is useful if no text should not be included in the raster image, but some place should be reserved in the image for later overlaying custom text over the image using HTML etc.',
  },
  optimize: {
    name: 'optimize',
    kind: 'boolean',
    propertyName: 'optimize',
    optionFlags: '--optimize',
    description:
      "Specifies whether the generated preview image should be optimized to reduce the image's file size while keeping their quaility. If enabled, the images will be optimized using [🤖/image/optimize](/docs/robots/image-optimize/).",
  },
  optimizePriority: {
    name: 'optimize_priority',
    kind: 'string',
    propertyName: 'optimizePriority',
    optionFlags: '--optimize-priority',
    description:
      'Specifies whether conversion speed or compression ratio is prioritized when optimizing images. Only used if `optimize` is enabled. Please see the [🤖/image/optimize documentation](/docs/robots/image-optimize/#param-priority) for more details.',
  },
  optimizeProgressive: {
    name: 'optimize_progressive',
    kind: 'boolean',
    propertyName: 'optimizeProgressive',
    optionFlags: '--optimize-progressive',
    description:
      'Specifies whether images should be interlaced, which makes the result image load progressively in browsers. Only used if `optimize` is enabled. Please see the [🤖/image/optimize documentation](/docs/robots/image-optimize/#param-progressive) for more details.',
  },
  clipFormat: {
    name: 'clip_format',
    kind: 'string',
    propertyName: 'clipFormat',
    optionFlags: '--clip-format',
    description:
      'The animated image format for the generated video clip. Only used if the `clip` strategy for video files is applied.\n\nPlease consult the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) for detailed information about the image formats and their characteristics. GIF enjoys the broadest support in software, but only supports a limit color palette. APNG supports a variety of color depths, but its lossless compression produces large images for videos. AVIF is a modern image format that offers great compression, but proper support for animations is still lacking in some browsers. WebP on the other hand, enjoys broad support while offering a great balance between small file sizes and good visual quality, making it the default clip format.',
  },
  clipOffset: {
    name: 'clip_offset',
    kind: 'number',
    propertyName: 'clipOffset',
    optionFlags: '--clip-offset',
    description:
      'The start position in seconds of where the clip is cut. Only used if the `clip` strategy for video files is applied. Be aware that for larger video only the first few MBs of the file may be imported to improve speed. Larger offsets may seek to a position outside of the imported part and thus fail to generate a clip.',
  },
  clipDuration: {
    name: 'clip_duration',
    kind: 'number',
    propertyName: 'clipDuration',
    optionFlags: '--clip-duration',
    description:
      'The duration in seconds of the generated video clip. Only used if the `clip` strategy for video files is applied. Be aware that a longer clip duration also results in a larger file size, which might be undesirable for previews.',
  },
  clipFramerate: {
    name: 'clip_framerate',
    kind: 'number',
    propertyName: 'clipFramerate',
    optionFlags: '--clip-framerate',
    description:
      'The framerate of the generated video clip. Only used if the `clip` strategy for video files is applied. Be aware that a higher framerate appears smoother but also results in a larger file size, which might be undesirable for previews.',
  },
  clipLoop: {
    name: 'clip_loop',
    kind: 'boolean',
    propertyName: 'clipLoop',
    optionFlags: '--clip-loop',
    description:
      'Specifies whether the generated animated image should loop forever (`true`) or stop after playing the animation once (`false`). Only used if the `clip` strategy for video files is applied.',
  },
} as const

const imageRemoveBackgroundCommandFields = {
  select: {
    name: 'select',
    kind: 'string',
    propertyName: 'select',
    optionFlags: '--select',
    description: 'Region to select and keep in the image. The other region is removed.',
  },
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description: 'Format of the generated image.',
  },
  provider: {
    name: 'provider',
    kind: 'string',
    propertyName: 'provider',
    optionFlags: '--provider',
    description: 'Provider to use for removing the background.',
  },
  model: {
    name: 'model',
    kind: 'string',
    propertyName: 'model',
    optionFlags: '--model',
    description:
      'Provider-specific model to use for removing the background. Mostly intended for testing and evaluation.',
  },
} as const

const imageOptimizeCommandFields = {
  priority: {
    name: 'priority',
    kind: 'string',
    propertyName: 'priority',
    optionFlags: '--priority',
    description:
      'Provides different algorithms for better or worse compression for your images, but that run slower or faster. The value `"conversion-speed"` will result in an average compression ratio of 18%. `"compression-ratio"` will result in an average compression ratio of 31%.',
  },
  progressive: {
    name: 'progressive',
    kind: 'boolean',
    propertyName: 'progressive',
    optionFlags: '--progressive',
    description:
      'Interlaces the image if set to `true`, which makes the result image load progressively in browsers. Instead of rendering the image from top to bottom, the browser will first show a low-res blurry version of the image which is then quickly replaced with the actual image as the data arrives. This greatly increases the user experience, but comes at a loss of about 10% of the file size reduction.',
  },
  preserveMetaData: {
    name: 'preserve_meta_data',
    kind: 'boolean',
    propertyName: 'preserveMetaData',
    optionFlags: '--preserve-meta-data',
    description:
      "Specifies if the image's metadata should be preserved during the optimization, or not. If it is not preserved, the file size is even further reduced. But be aware that this could strip a photographer's copyright information, which for obvious reasons can be frowned upon.",
  },
  fixBreakingImages: {
    name: 'fix_breaking_images',
    kind: 'boolean',
    propertyName: 'fixBreakingImages',
    optionFlags: '--fix-breaking-images',
    description:
      'If set to `true` this parameter tries to fix images that would otherwise make the underlying tool error out and thereby break your <dfn>Assemblies</dfn>. This can sometimes result in a larger file size, though.',
  },
} as const

const imageResizeCommandFields = {
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The output format for the modified image.\n\nSome of the most important available formats are `"jpg"`, `"png"`, `"gif"`, and `"tiff"`. For a complete lists of all formats that we can write to please check [our supported image formats list](/docs/supported-formats/image-formats/).\n\nIf `null` (default), then the input image\'s format will be used as the output format.\n\nIf you wish to convert to `"pdf"`, please consider [🤖/document/convert](/docs/robots/document-convert/) instead.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description:
      'Width of the result in pixels. If not specified, will default to the width of the original.',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description:
      'Height of the new image, in pixels. If not specified, will default to the height of the input image.',
  },
  resizeStrategy: {
    name: 'resize_strategy',
    kind: 'string',
    propertyName: 'resizeStrategy',
    optionFlags: '--resize-strategy',
    description: 'See the list of available [resize strategies](/docs/topics/resize-strategies/).',
  },
  zoom: {
    name: 'zoom',
    kind: 'boolean',
    propertyName: 'zoom',
    optionFlags: '--zoom',
    description:
      'If this is set to `false`, smaller images will not be stretched to the desired width and height. For details about the impact of zooming for your preferred resize strategy, see the list of available [resize strategies](/docs/topics/resize-strategies/).',
  },
  crop: {
    name: 'crop',
    kind: 'auto',
    propertyName: 'crop',
    optionFlags: '--crop',
    description:
      'Specify an object containing coordinates for the top left and bottom right corners of the rectangle to be cropped from the original image(s). The coordinate system is rooted in the top left corner of the image. Values can be integers for absolute pixel values or strings for percentage based values.\n\nFor example:\n\n```json\n{\n  "x1": 80,\n  "y1": 100,\n  "x2": "60%",\n  "y2": "80%"\n}\n```\n\nThis will crop the area from `(80, 100)` to `(600, 800)` from a 1000×1000 pixels image, which is a square whose width is 520px and height is 700px. If `crop` is set, the width and height parameters are ignored, and the `resize_strategy` is set to `crop` automatically.\n\nYou can also use a JSON string of such an object with coordinates in similar fashion:\n\n```json\n"{\\"x1\\": <Integer>, \\"y1\\": <Integer>, \\"x2\\": <Integer>, \\"y2\\": <Integer>}"\n```\n\nTo crop around human faces, see [🤖/image/facedetect](/docs/robots/image-facedetect/).',
  },
  gravity: {
    name: 'gravity',
    kind: 'string',
    propertyName: 'gravity',
    optionFlags: '--gravity',
    description:
      'The direction from which the image is to be cropped, when `"resize_strategy"` is set to `"crop"`, but no crop coordinates are defined.',
  },
  strip: {
    name: 'strip',
    kind: 'boolean',
    propertyName: 'strip',
    optionFlags: '--strip',
    description:
      'Strips all metadata from the image. This is useful to keep thumbnails as small as possible.',
  },
  alpha: {
    name: 'alpha',
    kind: 'string',
    propertyName: 'alpha',
    optionFlags: '--alpha',
    description: 'Gives control of the alpha/matte channel of an image.',
  },
  preclipAlpha: {
    name: 'preclip_alpha',
    kind: 'string',
    propertyName: 'preclipAlpha',
    optionFlags: '--preclip-alpha',
    description:
      'Gives control of the alpha/matte channel of an image before applying the clipping path via `clip: true`.',
  },
  flatten: {
    name: 'flatten',
    kind: 'boolean',
    propertyName: 'flatten',
    optionFlags: '--flatten',
    description:
      'Flattens all layers onto the specified background to achieve better results from transparent formats to non-transparent formats, as explained in the [ImageMagick documentation](https://www.imagemagick.org/script/command-line-options.php#layers).\n\nTo preserve animations, GIF files are not flattened when this is set to `true`. To flatten GIF animations, use the `frame` parameter.',
  },
  correctGamma: {
    name: 'correct_gamma',
    kind: 'boolean',
    propertyName: 'correctGamma',
    optionFlags: '--correct-gamma',
    description:
      'Prevents gamma errors [common in many image scaling algorithms](https://www.4p8.com/eric.brasseur/gamma.html).',
  },
  quality: {
    name: 'quality',
    kind: 'number',
    propertyName: 'quality',
    optionFlags: '--quality',
    description:
      'Controls the image compression for JPG and PNG images. Please also take a look at [🤖/image/optimize](/docs/robots/image-optimize/).',
  },
  adaptiveFiltering: {
    name: 'adaptive_filtering',
    kind: 'boolean',
    propertyName: 'adaptiveFiltering',
    optionFlags: '--adaptive-filtering',
    description:
      'Controls the image compression for PNG images. Setting to `true` results in smaller file size, while increasing processing time. It is encouraged to keep this option disabled.',
  },
  background: {
    name: 'background',
    kind: 'string',
    propertyName: 'background',
    optionFlags: '--background',
    description:
      'Either the hexadecimal code or [name](https://www.imagemagick.org/script/color.php#color_names) of the color used to fill the background (used for the `pad` resize strategy).\n\n**Note:** By default, the background of transparent images is changed to white. To preserve transparency, set `"background"` to `"none"`.',
  },
  frame: {
    name: 'frame',
    kind: 'number',
    propertyName: 'frame',
    optionFlags: '--frame',
    description:
      'Use this parameter when dealing with animated GIF files to specify which frame of the GIF is used for the operation. Specify `1` to use the first frame, `2` to use the second, and so on. `null` means all frames.',
  },
  colorspace: {
    name: 'colorspace',
    kind: 'string',
    propertyName: 'colorspace',
    optionFlags: '--colorspace',
    description:
      'Sets the image colorspace. For details about the available values, see the [ImageMagick documentation](https://www.imagemagick.org/script/command-line-options.php#colorspace). Please note that if you were using `"RGB"`, we recommend using `"sRGB"` instead as of 2014-02-04. ImageMagick might try to find the most efficient `colorspace` based on the color of an image, and default to e.g. `"Gray"`. To force colors, you might have to use this parameter in combination with `type: "TrueColor"`.',
  },
  type: {
    name: 'type',
    kind: 'string',
    propertyName: 'type',
    optionFlags: '--type',
    description:
      'Sets the image color type. For details about the available values, see the [ImageMagick documentation](https://www.imagemagick.org/script/command-line-options.php#type). If you\'re using `colorspace`, ImageMagick might try to find the most efficient based on the color of an image, and default to e.g. `"Gray"`. To force colors, you could e.g. set this parameter to `"TrueColor"`',
  },
  sepia: {
    name: 'sepia',
    kind: 'number',
    propertyName: 'sepia',
    optionFlags: '--sepia',
    description: 'Applies a sepia tone effect in percent.',
  },
  rotation: {
    name: 'rotation',
    kind: 'auto',
    propertyName: 'rotation',
    optionFlags: '--rotation',
    description:
      'Determines whether the image should be rotated. Use any number to specify the rotation angle in degrees (e.g., `90`, `180`, `270`, `360`, or precise values like `2.9`). Use the value `true` or `"auto"` to auto-rotate images that are rotated incorrectly or depend on EXIF rotation settings. Otherwise, use `false` to disable auto-fixing altogether.',
  },
  compress: {
    name: 'compress',
    kind: 'string',
    propertyName: 'compress',
    optionFlags: '--compress',
    description:
      'Specifies pixel compression for when the image is written. Compression is disabled by default.\n\nPlease also take a look at [🤖/image/optimize](/docs/robots/image-optimize/).',
  },
  blur: {
    name: 'blur',
    kind: 'string',
    propertyName: 'blur',
    optionFlags: '--blur',
    description:
      'Specifies gaussian blur, using a value with the form `{radius}x{sigma}`. The radius value specifies the size of area the operator should look at when spreading pixels, and should typically be either `"0"` or at least two times the sigma value. The sigma value is an approximation of how many pixels the image is "spread"; think of it as the size of the brush used to blur the image. This number is a floating point value, enabling small values like `"0.5"` to be used.',
  },
  blurRegions: {
    name: 'blur_regions',
    kind: 'json',
    propertyName: 'blurRegions',
    optionFlags: '--blur-regions',
    description:
      'Specifies an array of ellipse objects that should be blurred on the image. Each object has the following keys: `x`, `y`, `width`, `height`.  If `blur_regions` has a value, then the `blur` parameter is used as the strength of the blur for each region.',
  },
  brightness: {
    name: 'brightness',
    kind: 'number',
    propertyName: 'brightness',
    optionFlags: '--brightness',
    description:
      'Increases or decreases the brightness of the image by using a multiplier. For example `1.5` would increase the brightness by 50%, and `0.75` would decrease the brightness by 25%.',
  },
  saturation: {
    name: 'saturation',
    kind: 'number',
    propertyName: 'saturation',
    optionFlags: '--saturation',
    description:
      'Increases or decreases the saturation of the image by using a multiplier. For example `1.5` would increase the saturation by 50%, and `0.75` would decrease the saturation by 25%.',
  },
  hue: {
    name: 'hue',
    kind: 'number',
    propertyName: 'hue',
    optionFlags: '--hue',
    description:
      'Changes the hue by rotating the color of the image. The value `100` would produce no change whereas `0` and `200` will negate the colors in the image.',
  },
  contrast: {
    name: 'contrast',
    kind: 'number',
    propertyName: 'contrast',
    optionFlags: '--contrast',
    description:
      'Adjusts the contrast of the image. A value of `1` produces no change. Values below `1` decrease contrast (with `0` being minimum contrast), and values above `1` increase contrast (with `2` being maximum contrast). This works like the `brightness` parameter.',
  },
  watermarkUrl: {
    name: 'watermark_url',
    kind: 'string',
    propertyName: 'watermarkUrl',
    optionFlags: '--watermark-url',
    description:
      'A URL indicating a PNG image to be overlaid above this image. Please note that you can also  [supply the watermark via another Assembly Step](/docs/topics/use-parameter/#supplying-the-watermark-via-an-assembly-step). With watermarking you can add an image onto another image. This is usually used for logos.',
  },
  watermarkPosition: {
    name: 'watermark_position',
    kind: 'auto',
    propertyName: 'watermarkPosition',
    optionFlags: '--watermark-position',
    description:
      'The position at which the watermark is placed. The available options are `"center"`, `"top"`, `"bottom"`, `"left"`, and `"right"`. You can also combine options, such as `"bottom-right"`.\n\nAn array of possible values can also be specified, in which case one value will be selected at random, such as `[ "center", "left", "bottom-left", "bottom-right" ]`.\n\nThis setting puts the watermark in the specified corner. To use a specific pixel offset for the watermark, you will need to add the padding to the image itself.',
  },
  watermarkXOffset: {
    name: 'watermark_x_offset',
    kind: 'number',
    propertyName: 'watermarkXOffset',
    optionFlags: '--watermark-x-offset',
    description:
      "The x-offset in number of pixels at which the watermark will be placed in relation to the position it has due to `watermark_position`.\n\nValues can be both positive and negative and yield different results depending on the `watermark_position` parameter. Positive values move the watermark closer to the image's center point, whereas negative values move the watermark further away from the image's center point.",
  },
  watermarkYOffset: {
    name: 'watermark_y_offset',
    kind: 'number',
    propertyName: 'watermarkYOffset',
    optionFlags: '--watermark-y-offset',
    description:
      "The y-offset in number of pixels at which the watermark will be placed in relation to the position it has due to `watermark_position`.\n\nValues can be both positive and negative and yield different results depending on the `watermark_position` parameter. Positive values move the watermark closer to the image's center point, whereas negative values move the watermark further away from the image's center point.",
  },
  watermarkSize: {
    name: 'watermark_size',
    kind: 'string',
    propertyName: 'watermarkSize',
    optionFlags: '--watermark-size',
    description:
      'The size of the watermark, as a percentage.\n\nFor example, a value of `"50%"` means that size of the watermark will be 50% of the size of image on which it is placed. The exact sizing depends on `watermark_resize_strategy`, too.',
  },
  watermarkResizeStrategy: {
    name: 'watermark_resize_strategy',
    kind: 'string',
    propertyName: 'watermarkResizeStrategy',
    optionFlags: '--watermark-resize-strategy',
    description:
      'Available values are `"fit"`, `"min_fit"`, `"stretch"` and `"area"`.\n\nTo explain how the resize strategies work, let\'s assume our target image size is 800×800 pixels and our watermark image is 400×300 pixels. Let\'s also assume, the `watermark_size` parameter is set to `"25%"`.\n\nFor the `"fit"` resize strategy, the watermark is scaled so that the longer side of the watermark takes up 25% of the corresponding image side. And the other side is scaled according to the aspect ratio of the watermark image. So with our watermark, the width is the longer side, and 25% of the image size would be 200px. Hence, the watermark would be resized to 200×150 pixels. If the `watermark_size` was set to `"50%"`, it would be resized to 400×300 pixels (so just left at its original size).\n\nFor the `"min_fit"` resize strategy, the watermark is scaled so that the shorter side of the watermark takes up 25% of the corresponding image side. And the other side is scaled according to the aspect ratio of the watermark image. So with our watermark, the height is the shorter side, and 25% of the image size would be 200px. Hence, the watermark would be resized to 267×200 pixels. If the `watermark_size` was set to `"50%"`, it would be resized to 533×400 pixels (so larger than its original size).\n\nFor the `"stretch"` resize strategy, the watermark is stretched (meaning, it is resized without keeping its aspect ratio in mind) so that both sides take up 25% of the corresponding image side. Since our image is 800×800 pixels, for a watermark size of 25% the watermark would be resized to 200×200 pixels. Its height would appear stretched, because keeping the aspect ratio in mind it would be resized to 200×150 pixels instead.\n\nFor the `"area"` resize strategy, the watermark is resized (keeping its aspect ratio in check) so that it covers `"xx%"` of the image\'s surface area. The value from `watermark_size` is used for the percentage area size.',
  },
  watermarkOpacity: {
    name: 'watermark_opacity',
    kind: 'number',
    propertyName: 'watermarkOpacity',
    optionFlags: '--watermark-opacity',
    description:
      'The opacity of the watermark, where `0.0` is fully transparent and `1.0` is fully opaque.\n\nFor example, a value of `0.5` means the watermark will be 50% transparent, allowing the underlying image to show through. This is useful for subtle branding or when you want the watermark to be less obtrusive.',
  },
  watermarkRepeatX: {
    name: 'watermark_repeat_x',
    kind: 'boolean',
    propertyName: 'watermarkRepeatX',
    optionFlags: '--watermark-repeat-x',
    description:
      'When set to `true`, the watermark will be repeated horizontally across the entire width of the image.\n\nThis is useful for creating tiled watermark patterns that cover the full image and make it more difficult to crop out the watermark.',
  },
  watermarkRepeatY: {
    name: 'watermark_repeat_y',
    kind: 'boolean',
    propertyName: 'watermarkRepeatY',
    optionFlags: '--watermark-repeat-y',
    description:
      'When set to `true`, the watermark will be repeated vertically across the entire height of the image.\n\nThis is useful for creating tiled watermark patterns that cover the full image. Can be combined with `watermark_repeat_x` to tile in both directions.',
  },
  text: {
    name: 'text',
    kind: 'json',
    propertyName: 'text',
    optionFlags: '--text',
    description:
      'Text overlays to be applied to the image. Can be either a single text object or an array of text objects. Each text object contains text rules. The following text parameters are intended to be used as properties for your text overlays. Here is an example:\n\n```json\n"watermarked": {\n  "use": "resized",\n  "robot": "/image/resize",\n  "text": [\n    {\n      "text": "© 2018 Transloadit.com",\n      "size": 12,\n      "font": "Ubuntu",\n      "color": "#eeeeee",\n      "valign": "bottom",\n      "align": "right",\n      "x_offset": 16,\n      "y_offset": -10\n    }\n  ]\n}\n```',
  },
  progressive: {
    name: 'progressive',
    kind: 'boolean',
    propertyName: 'progressive',
    optionFlags: '--progressive',
    description:
      'Interlaces the image if set to `true`, which makes the image load progressively in browsers. Instead of rendering the image from top to bottom, the browser will first show a low-res blurry version of the images which is then quickly replaced with the actual image as the data arrives. This greatly increases the user experience, but comes at a cost of a file size increase by around 10%.',
  },
  transparent: {
    name: 'transparent',
    kind: 'string',
    propertyName: 'transparent',
    optionFlags: '--transparent',
    description: 'Make this color transparent within the image. Example: `"255,255,255"`.',
  },
  trimWhitespace: {
    name: 'trim_whitespace',
    kind: 'boolean',
    propertyName: 'trimWhitespace',
    optionFlags: '--trim-whitespace',
    description:
      'This determines if additional whitespace around the image should first be trimmed away. If you set this to `true` this parameter removes any edges that are exactly the same color as the corner pixels.',
  },
  clip: {
    name: 'clip',
    kind: 'auto',
    propertyName: 'clip',
    optionFlags: '--clip',
    description:
      'Apply the clipping path to other operations in the resize job, if one is present. If set to `true`, it will automatically take the first clipping path. If set to a String it finds a clipping path by that name.',
  },
  negate: {
    name: 'negate',
    kind: 'boolean',
    propertyName: 'negate',
    optionFlags: '--negate',
    description:
      'Replace each pixel with its complementary color, effectively negating the image. Especially useful when testing clipping.',
  },
  density: {
    name: 'density',
    kind: 'string',
    propertyName: 'density',
    optionFlags: '--density',
    description:
      'While in-memory quality and file format depth specifies the color resolution, the density of an image is the spatial (space) resolution of the image. That is the density (in pixels per inch) of an image and defines how far apart (or how big) the individual pixels are. It defines the size of the image in real world terms when displayed on devices or printed.\n\nYou can set this value to a specific `width` or in the format `width`x`height`.\n\nIf your converted image is unsharp, please try increasing density.',
  },
  monochrome: {
    name: 'monochrome',
    kind: 'boolean',
    propertyName: 'monochrome',
    optionFlags: '--monochrome',
    description:
      'Transform the image to black and white. This is a shortcut for setting the colorspace to Gray and type to Bilevel.',
  },
  shave: {
    name: 'shave',
    kind: 'auto',
    propertyName: 'shave',
    optionFlags: '--shave',
    description:
      'Shave pixels from the image edges. The value should be in the format `width` or `width`x`height` to specify the number of pixels to remove from each side.',
  },
} as const

const documentConvertCommandFields = {
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description: 'The desired format for document conversion.',
    required: true,
  },
  markdownFormat: {
    name: 'markdown_format',
    kind: 'string',
    propertyName: 'markdownFormat',
    optionFlags: '--markdown-format',
    description:
      'Markdown can be represented in several [variants](https://www.iana.org/assignments/markdown-variants/markdown-variants.xhtml), so when using this Robot to transform Markdown into HTML please specify which revision is being used.',
  },
  markdownTheme: {
    name: 'markdown_theme',
    kind: 'string',
    propertyName: 'markdownTheme',
    optionFlags: '--markdown-theme',
    description:
      'This parameter overhauls your Markdown files styling based on several canned presets.',
  },
  pdfMargin: {
    name: 'pdf_margin',
    kind: 'string',
    propertyName: 'pdfMargin',
    optionFlags: '--pdf-margin',
    description:
      'PDF Paper margins, separated by `,` and with units.\n\nWe support the following unit values: `px`, `in`, `cm`, `mm`.\n\nCurrently this parameter is only supported when converting from `html`.',
  },
  pdfPrintBackground: {
    name: 'pdf_print_background',
    kind: 'boolean',
    propertyName: 'pdfPrintBackground',
    optionFlags: '--pdf-print-background',
    description:
      'Print PDF background graphics.\n\nCurrently this parameter is only supported when converting from `html`.',
  },
  pdfFormat: {
    name: 'pdf_format',
    kind: 'string',
    propertyName: 'pdfFormat',
    optionFlags: '--pdf-format',
    description:
      'PDF paper format.\n\nCurrently this parameter is only supported when converting from `html`.',
  },
  pdfDisplayHeaderFooter: {
    name: 'pdf_display_header_footer',
    kind: 'boolean',
    propertyName: 'pdfDisplayHeaderFooter',
    optionFlags: '--pdf-display-header-footer',
    description:
      'Display PDF header and footer.\n\nCurrently this parameter is only supported when converting from `html`.',
  },
  pdfHeaderTemplate: {
    name: 'pdf_header_template',
    kind: 'string',
    propertyName: 'pdfHeaderTemplate',
    optionFlags: '--pdf-header-template',
    description:
      'HTML template for the PDF print header.\n\nShould be valid HTML markup with following classes used to inject printing values into them:\n- `date` formatted print date\n- `title` document title\n- `url` document location\n- `pageNumber` current page number\n- `totalPages` total pages in the document\n\nCurrently this parameter is only supported when converting from `html`, and requires `pdf_display_header_footer` to be enabled.\n\nTo change the formatting of the HTML element, the `font-size` must be specified in a wrapper. For example, to center the page number at the top of a page you\'d use the following HTML for the header template:\n\n```html\n<div style="font-size: 15px; width: 100%; text-align: center;"><span class="pageNumber"></span></div>\n```',
  },
  pdfFooterTemplate: {
    name: 'pdf_footer_template',
    kind: 'string',
    propertyName: 'pdfFooterTemplate',
    optionFlags: '--pdf-footer-template',
    description:
      'HTML template for the PDF print footer.\n\nShould use the same format as the `pdf_header_template`.\n\nCurrently this parameter is only supported when converting from `html`, and requires `pdf_display_header_footer` to be enabled.\n\nTo change the formatting of the HTML element, the `font-size` must be specified in a wrapper. For example, to center the page number in the footer you\'d use the following HTML for the footer template:\n\n```html\n<div style="font-size: 15px; width: 100%; text-align: center;"><span class="pageNumber"></span></div>\n```',
  },
} as const

const documentOptimizeCommandFields = {
  preset: {
    name: 'preset',
    kind: 'string',
    propertyName: 'preset',
    optionFlags: '--preset',
    description:
      'The quality preset to use for optimization. Each preset provides a different balance between file size and quality:\n\n- `screen` - Lowest quality, smallest file size. Best for screen viewing only. Images are downsampled to 72 DPI.\n- `ebook` - Good balance of quality and size. Suitable for most purposes. Images are downsampled to 150 DPI.\n- `printer` - High quality suitable for printing. Images are kept at 300 DPI.\n- `prepress` - Highest quality for professional printing. Minimal compression applied.',
  },
  imageDpi: {
    name: 'image_dpi',
    kind: 'number',
    propertyName: 'imageDpi',
    optionFlags: '--image-dpi',
    description:
      'Target DPI (dots per inch) for embedded images. When specified, this overrides the DPI setting from the preset.\n\nHigher DPI values result in better image quality but larger file sizes. Lower values produce smaller files but may result in pixelated images when printed.\n\nCommon values:\n- 72 - Screen viewing\n- 150 - eBooks and general documents\n- 300 - Print quality\n- 600 - High-quality print',
  },
  compressFonts: {
    name: 'compress_fonts',
    kind: 'boolean',
    propertyName: 'compressFonts',
    optionFlags: '--compress-fonts',
    description:
      'Whether to compress embedded fonts. When enabled, fonts are compressed to reduce file size.',
  },
  subsetFonts: {
    name: 'subset_fonts',
    kind: 'boolean',
    propertyName: 'subsetFonts',
    optionFlags: '--subset-fonts',
    description:
      "Whether to subset embedded fonts, keeping only the glyphs that are actually used in the document. This can significantly reduce file size for documents that only use a small portion of a font's character set.",
  },
  removeMetadata: {
    name: 'remove_metadata',
    kind: 'boolean',
    propertyName: 'removeMetadata',
    optionFlags: '--remove-metadata',
    description:
      'Whether to strip document metadata (title, author, keywords, etc.) from the PDF. This can provide a small reduction in file size and may be useful for privacy.',
  },
  linearize: {
    name: 'linearize',
    kind: 'boolean',
    propertyName: 'linearize',
    optionFlags: '--linearize',
    description:
      'Whether to linearize (optimize for Fast Web View) the output PDF. Linearized PDFs can begin displaying in a browser before they are fully downloaded, improving the user experience for web delivery.',
  },
  compatibility: {
    name: 'compatibility',
    kind: 'string',
    propertyName: 'compatibility',
    optionFlags: '--compatibility',
    description:
      'The PDF version compatibility level. Lower versions have broader compatibility but fewer features. Higher versions support more advanced features but may not open in older PDF readers.\n\n- `1.4` - Acrobat 5 compatibility, most widely supported\n- `1.5` - Acrobat 6 compatibility\n- `1.6` - Acrobat 7 compatibility\n- `1.7` - Acrobat 8+ compatibility (default)\n- `2.0` - PDF 2.0 standard',
  },
} as const

const documentThumbsCommandFields = {
  page: {
    name: 'page',
    kind: 'number',
    propertyName: 'page',
    optionFlags: '--page',
    description:
      'The PDF page that you want to convert to an image. By default the value is `null` which means that all pages will be converted into images.',
  },
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The format of the extracted image(s).\n\nIf you specify the value `"gif"`, then an animated gif cycling through all pages is created. Please check out [this demo](/demos/document-processing/convert-all-pages-of-a-document-into-an-animated-gif/) to learn more about this.',
  },
  delay: {
    name: 'delay',
    kind: 'number',
    propertyName: 'delay',
    optionFlags: '--delay',
    description:
      'If your output format is `"gif"` then this parameter sets the number of 100th seconds to pass before the next frame is shown in the animation. Set this to `100` for example to allow 1 second to pass between the frames of the animated gif.\n\nIf your output format is not `"gif"`, then this parameter does not have any effect.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description:
      'Width of the new image, in pixels. If not specified, will default to the width of the input image',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description:
      'Height of the new image, in pixels. If not specified, will default to the height of the input image',
  },
  resizeStrategy: {
    name: 'resize_strategy',
    kind: 'string',
    propertyName: 'resizeStrategy',
    optionFlags: '--resize-strategy',
    description: 'One of the [available resize strategies](/docs/topics/resize-strategies/).',
  },
  background: {
    name: 'background',
    kind: 'string',
    propertyName: 'background',
    optionFlags: '--background',
    description:
      'Either the hexadecimal code or [name](https://www.imagemagick.org/script/color.php#color_names) of the color used to fill the background (only used for the pad resize strategy).\n\nBy default, the background of transparent images is changed to white. For details about how to preserve transparency across all image types, see [this demo](/demos/image-manipulation/properly-preserve-transparency-across-all-image-types/).',
  },
  alpha: {
    name: 'alpha',
    kind: 'string',
    propertyName: 'alpha',
    optionFlags: '--alpha',
    description:
      'Change how the alpha channel of the resulting image should work. Valid values are `"Set"` to enable transparency and `"Remove"` to remove transparency.\n\nFor a list of all valid values please check the ImageMagick documentation [here](http://www.imagemagick.org/script/command-line-options.php#alpha).',
  },
  density: {
    name: 'density',
    kind: 'string',
    propertyName: 'density',
    optionFlags: '--density',
    description:
      'While in-memory quality and file format depth specifies the color resolution, the density of an image is the spatial (space) resolution of the image. That is the density (in pixels per inch) of an image and defines how far apart (or how big) the individual pixels are. It defines the size of the image in real world terms when displayed on devices or printed.\n\nYou can set this value to a specific `width` or in the format `width`x`height`.\n\nIf your converted image has a low resolution, please try using the density parameter to resolve that.',
  },
  antialiasing: {
    name: 'antialiasing',
    kind: 'boolean',
    propertyName: 'antialiasing',
    optionFlags: '--antialiasing',
    description:
      'Controls whether or not antialiasing is used to remove jagged edges from text or images in a document.',
  },
  colorspace: {
    name: 'colorspace',
    kind: 'string',
    propertyName: 'colorspace',
    optionFlags: '--colorspace',
    description:
      'Sets the image colorspace. For details about the available values, see the [ImageMagick documentation](https://www.imagemagick.org/script/command-line-options.php#colorspace).\n\nPlease note that if you were using `"RGB"`, we recommend using `"sRGB"`. ImageMagick might try to find the most efficient `colorspace` based on the color of an image, and default to e.g. `"Gray"`. To force colors, you might then have to use this parameter.',
  },
  trimWhitespace: {
    name: 'trim_whitespace',
    kind: 'boolean',
    propertyName: 'trimWhitespace',
    optionFlags: '--trim-whitespace',
    description:
      "This determines if additional whitespace around the PDF should first be trimmed away before it is converted to an image. If you set this to `true` only the real PDF page contents will be shown in the image.\n\nIf you need to reflect the PDF's dimensions in your image, it is generally a good idea to set this to `false`.",
  },
  pdfUseCropbox: {
    name: 'pdf_use_cropbox',
    kind: 'boolean',
    propertyName: 'pdfUseCropbox',
    optionFlags: '--pdf-use-cropbox',
    description:
      "Some PDF documents lie about their dimensions. For instance they'll say they are landscape, but when opened in decent Desktop readers, it's really in portrait mode. This can happen if the document has a cropbox defined. When this option is enabled (by default), the cropbox is leading in determining the dimensions of the resulting thumbnails.",
  },
  turbo: {
    name: 'turbo',
    kind: 'boolean',
    propertyName: 'turbo',
    optionFlags: '--turbo',
    description:
      "If you set this to `false`, the robot will not emit files as they become available. This is useful if you are only interested in the final result and not in the intermediate steps.\n\nAlso, extracted pages will be resized a lot faster as they are sent off to other machines for the resizing. This is especially useful for large documents with many pages to get up to 20 times faster processing.\n\nTurbo Mode increases pricing, though, in that the input document's file size is added for every extracted page. There are no performance benefits nor increased charges for single-page documents.",
  },
} as const

const audioWaveformCommandFields = {
  ffmpeg: {
    name: 'ffmpeg',
    kind: 'json',
    propertyName: 'ffmpeg',
    optionFlags: '--ffmpeg',
    description:
      'A parameter object to be passed to FFmpeg. If a preset is used, the options specified are merged on top of the ones from the preset. For available options, see the [FFmpeg documentation](https://ffmpeg.org/ffmpeg-doc.html). Options specified here take precedence over the preset options.',
  },
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The format of the result file. Can be `"image"` or `"json"`. If `"image"` is supplied, a PNG image will be created, otherwise a JSON file.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description: 'The width of the resulting image if the format `"image"` was selected.',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description: 'The height of the resulting image if the format `"image"` was selected.',
  },
  antialiasing: {
    name: 'antialiasing',
    kind: 'auto',
    propertyName: 'antialiasing',
    optionFlags: '--antialiasing',
    description:
      'Either a value of `0` or `1`, or `true`/`false`, corresponding to if you want to enable antialiasing to achieve smoother edges in the waveform graph or not.',
  },
  backgroundColor: {
    name: 'background_color',
    kind: 'string',
    propertyName: 'backgroundColor',
    optionFlags: '--background-color',
    description:
      'The background color of the resulting image in the "rrggbbaa" format (red, green, blue, alpha), if the format `"image"` was selected.',
  },
  centerColor: {
    name: 'center_color',
    kind: 'string',
    propertyName: 'centerColor',
    optionFlags: '--center-color',
    description:
      'The color used in the center of the gradient. The format is "rrggbbaa" (red, green, blue, alpha).',
  },
  outerColor: {
    name: 'outer_color',
    kind: 'string',
    propertyName: 'outerColor',
    optionFlags: '--outer-color',
    description:
      'The color used in the outer parts of the gradient. The format is "rrggbbaa" (red, green, blue, alpha).',
  },
  style: {
    name: 'style',
    kind: 'string',
    propertyName: 'style',
    optionFlags: '--style',
    description:
      'Waveform style version.\n\n- `"v0"`: Legacy waveform generation (default).\n- `"v1"`: Advanced waveform generation with additional parameters.\n\nFor backwards compatibility, numeric values `0`, `1`, `2` are also accepted and mapped to `"v0"` (0) and `"v1"` (1/2).',
  },
  splitChannels: {
    name: 'split_channels',
    kind: 'boolean',
    propertyName: 'splitChannels',
    optionFlags: '--split-channels',
    description:
      'Available when style is `"v1"`. If set to `true`, outputs multi-channel waveform data or image files, one per channel.',
  },
  zoom: {
    name: 'zoom',
    kind: 'number',
    propertyName: 'zoom',
    optionFlags: '--zoom',
    description:
      'Available when style is `"v1"`. Zoom level in samples per pixel. This parameter cannot be used together with `pixels_per_second`.',
  },
  pixelsPerSecond: {
    name: 'pixels_per_second',
    kind: 'number',
    propertyName: 'pixelsPerSecond',
    optionFlags: '--pixels-per-second',
    description:
      'Available when style is `"v1"`. Zoom level in pixels per second. This parameter cannot be used together with `zoom`.',
  },
  bits: {
    name: 'bits',
    kind: 'number',
    propertyName: 'bits',
    optionFlags: '--bits',
    description: 'Available when style is `"v1"`. Bit depth for waveform data. Can be 8 or 16.',
  },
  start: {
    name: 'start',
    kind: 'number',
    propertyName: 'start',
    optionFlags: '--start',
    description: 'Available when style is `"v1"`. Start time in seconds.',
  },
  end: {
    name: 'end',
    kind: 'number',
    propertyName: 'end',
    optionFlags: '--end',
    description: 'Available when style is `"v1"`. End time in seconds (0 means end of audio).',
  },
  colors: {
    name: 'colors',
    kind: 'string',
    propertyName: 'colors',
    optionFlags: '--colors',
    description:
      'Available when style is `"v1"`. Color scheme to use. Can be "audition" or "audacity".',
  },
  borderColor: {
    name: 'border_color',
    kind: 'string',
    propertyName: 'borderColor',
    optionFlags: '--border-color',
    description: 'Available when style is `"v1"`. Border color in "rrggbbaa" format.',
  },
  waveformStyle: {
    name: 'waveform_style',
    kind: 'string',
    propertyName: 'waveformStyle',
    optionFlags: '--waveform-style',
    description: 'Available when style is `"v1"`. Waveform style. Can be "normal" or "bars".',
  },
  barWidth: {
    name: 'bar_width',
    kind: 'number',
    propertyName: 'barWidth',
    optionFlags: '--bar-width',
    description:
      'Available when style is `"v1"`. Width of bars in pixels when waveform_style is "bars".',
  },
  barGap: {
    name: 'bar_gap',
    kind: 'number',
    propertyName: 'barGap',
    optionFlags: '--bar-gap',
    description:
      'Available when style is `"v1"`. Gap between bars in pixels when waveform_style is "bars".',
  },
  barStyle: {
    name: 'bar_style',
    kind: 'string',
    propertyName: 'barStyle',
    optionFlags: '--bar-style',
    description: 'Available when style is `"v1"`. Bar style when waveform_style is "bars".',
  },
  axisLabelColor: {
    name: 'axis_label_color',
    kind: 'string',
    propertyName: 'axisLabelColor',
    optionFlags: '--axis-label-color',
    description: 'Available when style is `"v1"`. Color for axis labels in "rrggbbaa" format.',
  },
  noAxisLabels: {
    name: 'no_axis_labels',
    kind: 'boolean',
    propertyName: 'noAxisLabels',
    optionFlags: '--no-axis-labels',
    description:
      'Available when style is `"v1"`. If set to `true`, renders waveform image without axis labels.',
  },
  withAxisLabels: {
    name: 'with_axis_labels',
    kind: 'boolean',
    propertyName: 'withAxisLabels',
    optionFlags: '--with-axis-labels',
    description:
      'Available when style is `"v1"`. If set to `true`, renders waveform image with axis labels.',
  },
  amplitudeScale: {
    name: 'amplitude_scale',
    kind: 'number',
    propertyName: 'amplitudeScale',
    optionFlags: '--amplitude-scale',
    description: 'Available when style is `"v1"`. Amplitude scale factor.',
  },
  compression: {
    name: 'compression',
    kind: 'number',
    propertyName: 'compression',
    optionFlags: '--compression',
    description:
      'Available when style is `"v1"`. PNG compression level: 0 (none) to 9 (best), or -1 (default). Only applicable when format is "image".',
  },
} as const

const textSpeakCommandFields = {
  prompt: {
    name: 'prompt',
    kind: 'string',
    propertyName: 'prompt',
    optionFlags: '--prompt',
    description:
      'Which text to speak. You can also set this to `null` and supply an input text file.',
  },
  provider: {
    name: 'provider',
    kind: 'string',
    propertyName: 'provider',
    optionFlags: '--provider',
    description:
      'Which AI provider to leverage.\n\nTransloadit outsources this task and abstracts the interface so you can expect the same data structures, but different latencies and information being returned. Different cloud vendors have different areas they shine in, and we recommend to try out and see what yields the best results for your use case.',
    required: true,
  },
  targetLanguage: {
    name: 'target_language',
    kind: 'string',
    propertyName: 'targetLanguage',
    optionFlags: '--target-language',
    description:
      'The written language of the document. This will also be the language of the spoken text.\n\nThe language should be specified in the [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) format, such as `"en-GB"`, `"de-DE"` or `"fr-FR"`. Please consult the list of supported languages and voices.',
  },
  voice: {
    name: 'voice',
    kind: 'string',
    propertyName: 'voice',
    optionFlags: '--voice',
    description:
      'The gender to be used for voice synthesis. Please consult the list of supported languages and voices.',
  },
  ssml: {
    name: 'ssml',
    kind: 'boolean',
    propertyName: 'ssml',
    optionFlags: '--ssml',
    description:
      'Supply [Speech Synthesis Markup Language](https://en.wikipedia.org/wiki/Speech_Synthesis_Markup_Language) instead of raw text, in order to gain more control over how your text is voiced, including rests and pronounciations.\n\nPlease see the supported syntaxes for [AWS](https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html) and [GCP](https://cloud.google.com/text-to-speech/docs/ssml).',
  },
} as const

const videoThumbsCommandFields = {
  ffmpeg: {
    name: 'ffmpeg',
    kind: 'json',
    propertyName: 'ffmpeg',
    optionFlags: '--ffmpeg',
    description:
      'A parameter object to be passed to FFmpeg. If a preset is used, the options specified are merged on top of the ones from the preset. For available options, see the [FFmpeg documentation](https://ffmpeg.org/ffmpeg-doc.html). Options specified here take precedence over the preset options.',
  },
  count: {
    name: 'count',
    kind: 'number',
    propertyName: 'count',
    optionFlags: '--count',
    description:
      'The number of thumbnails to be extracted. As some videos have incorrect durations, the actual number of thumbnails generated may be less in rare cases. The maximum number of thumbnails we currently allow is 999.\n\nThe thumbnails are taken at regular intervals, determined by dividing the video duration by the count. For example, a count of 3 will produce thumbnails at 25%, 50% and 75% through the video.\n\nTo extract thumbnails for specific timestamps, use the `offsets` parameter.',
  },
  offsets: {
    name: 'offsets',
    kind: 'json',
    propertyName: 'offsets',
    optionFlags: '--offsets',
    description:
      'An array of offsets representing seconds of the file duration, such as `[ 2, 45, 120 ]`. Millisecond durations of a file can also be used by using decimal place values. For example, an offset from 1250 milliseconds would be represented with `1.25`. Offsets can also be percentage values such as `[ "2%", "50%", "75%" ]`.\n\nThis option cannot be used with the `count` parameter, and takes precedence if both are specified. Out-of-range offsets are silently ignored.',
  },
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The format of the extracted thumbnail. Supported values are `"jpg"`, `"jpeg"` and `"png"`. Even if you specify the format to be `"jpeg"` the resulting thumbnails will have a `"jpg"` file extension.',
  },
  width: {
    name: 'width',
    kind: 'number',
    propertyName: 'width',
    optionFlags: '--width',
    description:
      'The width of the thumbnail, in pixels. Defaults to the original width of the video.',
  },
  height: {
    name: 'height',
    kind: 'number',
    propertyName: 'height',
    optionFlags: '--height',
    description:
      'The height of the thumbnail, in pixels. Defaults to the original height of the video.',
  },
  resizeStrategy: {
    name: 'resize_strategy',
    kind: 'string',
    propertyName: 'resizeStrategy',
    optionFlags: '--resize-strategy',
    description: 'One of the [available resize strategies](/docs/topics/resize-strategies/).',
  },
  background: {
    name: 'background',
    kind: 'string',
    propertyName: 'background',
    optionFlags: '--background',
    description:
      'The background color of the resulting thumbnails in the `"rrggbbaa"` format (red, green, blue, alpha) when used with the `"pad"` resize strategy. The default color is black.',
  },
  rotate: {
    name: 'rotate',
    kind: 'number',
    propertyName: 'rotate',
    optionFlags: '--rotate',
    description:
      'Forces the video to be rotated by the specified degree integer. Currently, only multiples of 90 are supported. We automatically correct the orientation of many videos when the orientation is provided by the camera. This option is only useful for videos requiring rotation because it was not detected by the camera.',
  },
  inputCodec: {
    name: 'input_codec',
    kind: 'string',
    propertyName: 'inputCodec',
    optionFlags: '--input-codec',
    description:
      'Specifies the input codec to use when decoding the video. This is useful for videos with special codecs that require specific decoders.',
  },
} as const

const fileCompressCommandFields = {
  format: {
    name: 'format',
    kind: 'string',
    propertyName: 'format',
    optionFlags: '--format',
    description:
      'The format of the archive to be created. Supported values are `"tar"` and `"zip"`.\n\nNote that `"tar"` without setting `gzip` to `true` results in an archive that\'s not compressed in any way.',
  },
  gzip: {
    name: 'gzip',
    kind: 'boolean',
    propertyName: 'gzip',
    optionFlags: '--gzip',
    description:
      'Determines if the result archive should also be gzipped. Gzip compression is only applied if you use the `"tar"` format.',
  },
  password: {
    name: 'password',
    kind: 'string',
    propertyName: 'password',
    optionFlags: '--password',
    description:
      'This allows you to encrypt all archive contents with a password and thereby protect it against unauthorized use. To unzip the archive, the user will need to provide the password in a text input field prompt.\n\nThis parameter has no effect if the format parameter is anything other than `"zip"`.',
  },
  compressionLevel: {
    name: 'compression_level',
    kind: 'number',
    propertyName: 'compressionLevel',
    optionFlags: '--compression-level',
    description:
      'Determines how fiercely to try to compress the archive. `-0` is compressionless, which is suitable for media that is already compressed. `-1` is fastest with lowest compression. `-9` is slowest with the highest compression.\n\nIf you are using `-0` in combination with the `tar` format with `gzip` enabled, consider setting `gzip: false` instead. This results in a plain Tar archive, meaning it already has no compression.',
  },
  fileLayout: {
    name: 'file_layout',
    kind: 'string',
    propertyName: 'fileLayout',
    optionFlags: '--file-layout',
    description:
      'Determines if the result archive should contain all files in one directory (value for this is `"simple"`) or in subfolders according to the explanation below (value for this is `"advanced"`). The `"relative-path"` option preserves the relative directory structure of the input files.\n\nFiles with same names are numbered in the `"simple"` file layout to avoid naming collisions.',
  },
  archiveName: {
    name: 'archive_name',
    kind: 'string',
    propertyName: 'archiveName',
    optionFlags: '--archive-name',
    description: 'The name of the archive file to be created (without the file extension).',
  },
} as const
const imageGenerateCommandDefinition = {
  outputMode: 'file',
  outputDescription: 'Write the result to this path',
  execution: {
    kind: 'single-step',
    schema: robotImageGenerateInstructionsSchema,
    fields: Object.values(imageGenerateCommandFields),
    fixedValues: {
      robot: '/image/generate',
      result: true,
    },
    resultStepName: 'generate',
  },
} as const

const previewGenerateCommandDefinition = {
  commandLabel: 'preview generate',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotFilePreviewInstructionsSchema,
    fields: Object.values(previewGenerateCommandFields),
    fixedValues: {
      robot: '/file/preview',
      result: true,
      use: ':original',
    },
    resultStepName: 'generate',
  },
} as const

const imageRemoveBackgroundCommandDefinition = {
  commandLabel: 'image remove-background',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotImageBgremoveInstructionsSchema,
    fields: Object.values(imageRemoveBackgroundCommandFields),
    fixedValues: {
      robot: '/image/bgremove',
      result: true,
      use: ':original',
    },
    resultStepName: 'remove_background',
  },
} as const

const imageOptimizeCommandDefinition = {
  commandLabel: 'image optimize',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotImageOptimizeInstructionsSchema,
    fields: Object.values(imageOptimizeCommandFields),
    fixedValues: {
      robot: '/image/optimize',
      result: true,
      use: ':original',
    },
    resultStepName: 'optimize',
  },
} as const

const imageResizeCommandDefinition = {
  commandLabel: 'image resize',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotImageResizeInstructionsSchema,
    fields: Object.values(imageResizeCommandFields),
    fixedValues: {
      robot: '/image/resize',
      result: true,
      use: ':original',
    },
    resultStepName: 'resize',
  },
} as const

const documentConvertCommandDefinition = {
  commandLabel: 'document convert',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotDocumentConvertInstructionsSchema,
    fields: Object.values(documentConvertCommandFields),
    fixedValues: {
      robot: '/document/convert',
      result: true,
      use: ':original',
    },
    resultStepName: 'convert',
  },
} as const

const documentOptimizeCommandDefinition = {
  commandLabel: 'document optimize',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotDocumentOptimizeInstructionsSchema,
    fields: Object.values(documentOptimizeCommandFields),
    fixedValues: {
      robot: '/document/optimize',
      result: true,
      use: ':original',
    },
    resultStepName: 'optimize',
  },
} as const

const documentAutoRotateCommandDefinition = {
  commandLabel: 'document auto-rotate',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotDocumentAutorotateInstructionsSchema,
    fields: [],
    fixedValues: {
      robot: '/document/autorotate',
      result: true,
      use: ':original',
    },
    resultStepName: 'auto_rotate',
  },
} as const

const documentThumbsCommandDefinition = {
  commandLabel: 'document thumbs',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'directory',
  outputDescription: 'Write the results to this directory',
  execution: {
    kind: 'single-step',
    schema: robotDocumentThumbsInstructionsSchema,
    fields: Object.values(documentThumbsCommandFields),
    fixedValues: {
      robot: '/document/thumbs',
      result: true,
      use: ':original',
    },
    resultStepName: 'thumbs',
  },
} as const

const audioWaveformCommandDefinition = {
  commandLabel: 'audio waveform',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotAudioWaveformInstructionsSchema,
    fields: Object.values(audioWaveformCommandFields),
    fixedValues: {
      robot: '/audio/waveform',
      result: true,
      use: ':original',
    },
    resultStepName: 'waveform',
  },
} as const

const textSpeakCommandDefinition = {
  commandLabel: 'text speak',
  inputPolicy: {
    kind: 'optional',
    field: 'prompt',
    attachUseWhenInputsProvided: true,
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotTextSpeakInstructionsSchema,
    fields: Object.values(textSpeakCommandFields),
    fixedValues: {
      robot: '/text/speak',
      result: true,
    },
    resultStepName: 'speak',
  },
} as const

const videoThumbsCommandDefinition = {
  commandLabel: 'video thumbs',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'directory',
  outputDescription: 'Write the results to this directory',
  execution: {
    kind: 'single-step',
    schema: robotVideoThumbsInstructionsSchema,
    fields: Object.values(videoThumbsCommandFields),
    fixedValues: {
      robot: '/video/thumbs',
      result: true,
      use: ':original',
    },
    resultStepName: 'thumbs',
  },
} as const

const videoEncodeHlsCommandDefinition = {
  commandLabel: 'video encode-hls',
  inputPolicy: { kind: 'required' },
  outputMode: 'directory',
  outputDescription: 'Write the results to this directory',
  execution: {
    kind: 'template',
    templateId: 'builtin/encode-hls-video@latest',
  },
} as const

const fileCompressCommandDefinition = {
  commandLabel: 'file compress',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'file',
  outputDescription: 'Write the result to this path or directory',
  execution: {
    kind: 'single-step',
    schema: robotFileCompressInstructionsSchema,
    fields: Object.values(fileCompressCommandFields),
    fixedValues: {
      robot: '/file/compress',
      result: true,
      use: {
        steps: [':original'],
        bundle_steps: true,
      },
    },
    resultStepName: 'compress',
  },
} as const

const fileDecompressCommandDefinition = {
  commandLabel: 'file decompress',
  inputPolicy: {
    kind: 'required',
  },
  outputMode: 'directory',
  outputDescription: 'Write the results to this directory',
  execution: {
    kind: 'single-step',
    schema: robotFileDecompressInstructionsSchema,
    fields: [],
    fixedValues: {
      robot: '/file/decompress',
      result: true,
      use: ':original',
    },
    resultStepName: 'decompress',
  },
} as const

class ImageGenerateCommand extends GeneratedNoInputIntentCommand {
  static override paths = [['image', 'generate']]

  static override intentDefinition = imageGenerateCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate images from text prompts',
    details: 'Runs `/image/generate` and writes the result to `--out`.',
    examples: [
      [
        'Run the command',
        'transloadit image generate --prompt "A red bicycle in a studio" --out output.png',
      ],
    ],
  })

  model = createIntentOption(imageGenerateCommandFields.model)

  prompt = createIntentOption(imageGenerateCommandFields.prompt)

  format = createIntentOption(imageGenerateCommandFields.format)

  seed = createIntentOption(imageGenerateCommandFields.seed)

  aspectRatio = createIntentOption(imageGenerateCommandFields.aspectRatio)

  height = createIntentOption(imageGenerateCommandFields.height)

  width = createIntentOption(imageGenerateCommandFields.width)

  style = createIntentOption(imageGenerateCommandFields.style)

  numOutputs = createIntentOption(imageGenerateCommandFields.numOutputs)
}

class PreviewGenerateCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['preview', 'generate']]

  static override intentDefinition = previewGenerateCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate a preview thumbnail',
    details: 'Runs `/file/preview` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit preview generate --input input.file --out output.file'],
    ],
  })

  format = createIntentOption(previewGenerateCommandFields.format)

  width = createIntentOption(previewGenerateCommandFields.width)

  height = createIntentOption(previewGenerateCommandFields.height)

  resizeStrategy = createIntentOption(previewGenerateCommandFields.resizeStrategy)

  background = createIntentOption(previewGenerateCommandFields.background)

  strategy = createIntentOption(previewGenerateCommandFields.strategy)

  artworkOuterColor = createIntentOption(previewGenerateCommandFields.artworkOuterColor)

  artworkCenterColor = createIntentOption(previewGenerateCommandFields.artworkCenterColor)

  waveformCenterColor = createIntentOption(previewGenerateCommandFields.waveformCenterColor)

  waveformOuterColor = createIntentOption(previewGenerateCommandFields.waveformOuterColor)

  waveformHeight = createIntentOption(previewGenerateCommandFields.waveformHeight)

  waveformWidth = createIntentOption(previewGenerateCommandFields.waveformWidth)

  iconStyle = createIntentOption(previewGenerateCommandFields.iconStyle)

  iconTextColor = createIntentOption(previewGenerateCommandFields.iconTextColor)

  iconTextFont = createIntentOption(previewGenerateCommandFields.iconTextFont)

  iconTextContent = createIntentOption(previewGenerateCommandFields.iconTextContent)

  optimize = createIntentOption(previewGenerateCommandFields.optimize)

  optimizePriority = createIntentOption(previewGenerateCommandFields.optimizePriority)

  optimizeProgressive = createIntentOption(previewGenerateCommandFields.optimizeProgressive)

  clipFormat = createIntentOption(previewGenerateCommandFields.clipFormat)

  clipOffset = createIntentOption(previewGenerateCommandFields.clipOffset)

  clipDuration = createIntentOption(previewGenerateCommandFields.clipDuration)

  clipFramerate = createIntentOption(previewGenerateCommandFields.clipFramerate)

  clipLoop = createIntentOption(previewGenerateCommandFields.clipLoop)
}

class ImageRemoveBackgroundCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['image', 'remove-background']]

  static override intentDefinition = imageRemoveBackgroundCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Remove the background from images',
    details: 'Runs `/image/bgremove` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit image remove-background --input input.png --out output.png'],
    ],
  })

  select = createIntentOption(imageRemoveBackgroundCommandFields.select)

  format = createIntentOption(imageRemoveBackgroundCommandFields.format)

  provider = createIntentOption(imageRemoveBackgroundCommandFields.provider)

  model = createIntentOption(imageRemoveBackgroundCommandFields.model)
}

class ImageOptimizeCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['image', 'optimize']]

  static override intentDefinition = imageOptimizeCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Optimize images without quality loss',
    details: 'Runs `/image/optimize` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit image optimize --input input.png --out output.png'],
    ],
  })

  priority = createIntentOption(imageOptimizeCommandFields.priority)

  progressive = createIntentOption(imageOptimizeCommandFields.progressive)

  preserveMetaData = createIntentOption(imageOptimizeCommandFields.preserveMetaData)

  fixBreakingImages = createIntentOption(imageOptimizeCommandFields.fixBreakingImages)
}

class ImageResizeCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['image', 'resize']]

  static override intentDefinition = imageResizeCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Convert, resize, or watermark images',
    details: 'Runs `/image/resize` on each input file and writes the result to `--out`.',
    examples: [['Run the command', 'transloadit image resize --input input.png --out output.png']],
  })

  format = createIntentOption(imageResizeCommandFields.format)

  width = createIntentOption(imageResizeCommandFields.width)

  height = createIntentOption(imageResizeCommandFields.height)

  resizeStrategy = createIntentOption(imageResizeCommandFields.resizeStrategy)

  zoom = createIntentOption(imageResizeCommandFields.zoom)

  crop = createIntentOption(imageResizeCommandFields.crop)

  gravity = createIntentOption(imageResizeCommandFields.gravity)

  strip = createIntentOption(imageResizeCommandFields.strip)

  alpha = createIntentOption(imageResizeCommandFields.alpha)

  preclipAlpha = createIntentOption(imageResizeCommandFields.preclipAlpha)

  flatten = createIntentOption(imageResizeCommandFields.flatten)

  correctGamma = createIntentOption(imageResizeCommandFields.correctGamma)

  quality = createIntentOption(imageResizeCommandFields.quality)

  adaptiveFiltering = createIntentOption(imageResizeCommandFields.adaptiveFiltering)

  background = createIntentOption(imageResizeCommandFields.background)

  frame = createIntentOption(imageResizeCommandFields.frame)

  colorspace = createIntentOption(imageResizeCommandFields.colorspace)

  type = createIntentOption(imageResizeCommandFields.type)

  sepia = createIntentOption(imageResizeCommandFields.sepia)

  rotation = createIntentOption(imageResizeCommandFields.rotation)

  compress = createIntentOption(imageResizeCommandFields.compress)

  blur = createIntentOption(imageResizeCommandFields.blur)

  blurRegions = createIntentOption(imageResizeCommandFields.blurRegions)

  brightness = createIntentOption(imageResizeCommandFields.brightness)

  saturation = createIntentOption(imageResizeCommandFields.saturation)

  hue = createIntentOption(imageResizeCommandFields.hue)

  contrast = createIntentOption(imageResizeCommandFields.contrast)

  watermarkUrl = createIntentOption(imageResizeCommandFields.watermarkUrl)

  watermarkPosition = createIntentOption(imageResizeCommandFields.watermarkPosition)

  watermarkXOffset = createIntentOption(imageResizeCommandFields.watermarkXOffset)

  watermarkYOffset = createIntentOption(imageResizeCommandFields.watermarkYOffset)

  watermarkSize = createIntentOption(imageResizeCommandFields.watermarkSize)

  watermarkResizeStrategy = createIntentOption(imageResizeCommandFields.watermarkResizeStrategy)

  watermarkOpacity = createIntentOption(imageResizeCommandFields.watermarkOpacity)

  watermarkRepeatX = createIntentOption(imageResizeCommandFields.watermarkRepeatX)

  watermarkRepeatY = createIntentOption(imageResizeCommandFields.watermarkRepeatY)

  text = createIntentOption(imageResizeCommandFields.text)

  progressive = createIntentOption(imageResizeCommandFields.progressive)

  transparent = createIntentOption(imageResizeCommandFields.transparent)

  trimWhitespace = createIntentOption(imageResizeCommandFields.trimWhitespace)

  clip = createIntentOption(imageResizeCommandFields.clip)

  negate = createIntentOption(imageResizeCommandFields.negate)

  density = createIntentOption(imageResizeCommandFields.density)

  monochrome = createIntentOption(imageResizeCommandFields.monochrome)

  shave = createIntentOption(imageResizeCommandFields.shave)
}

class DocumentConvertCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['document', 'convert']]

  static override intentDefinition = documentConvertCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Convert documents into different formats',
    details: 'Runs `/document/convert` on each input file and writes the result to `--out`.',
    examples: [
      [
        'Run the command',
        'transloadit document convert --input input.pdf --format pdf --out output.pdf',
      ],
    ],
  })

  format = createIntentOption(documentConvertCommandFields.format)

  markdownFormat = createIntentOption(documentConvertCommandFields.markdownFormat)

  markdownTheme = createIntentOption(documentConvertCommandFields.markdownTheme)

  pdfMargin = createIntentOption(documentConvertCommandFields.pdfMargin)

  pdfPrintBackground = createIntentOption(documentConvertCommandFields.pdfPrintBackground)

  pdfFormat = createIntentOption(documentConvertCommandFields.pdfFormat)

  pdfDisplayHeaderFooter = createIntentOption(documentConvertCommandFields.pdfDisplayHeaderFooter)

  pdfHeaderTemplate = createIntentOption(documentConvertCommandFields.pdfHeaderTemplate)

  pdfFooterTemplate = createIntentOption(documentConvertCommandFields.pdfFooterTemplate)
}

class DocumentOptimizeCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['document', 'optimize']]

  static override intentDefinition = documentOptimizeCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Reduce PDF file size',
    details: 'Runs `/document/optimize` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit document optimize --input input.pdf --out output.pdf'],
    ],
  })

  preset = createIntentOption(documentOptimizeCommandFields.preset)

  imageDpi = createIntentOption(documentOptimizeCommandFields.imageDpi)

  compressFonts = createIntentOption(documentOptimizeCommandFields.compressFonts)

  subsetFonts = createIntentOption(documentOptimizeCommandFields.subsetFonts)

  removeMetadata = createIntentOption(documentOptimizeCommandFields.removeMetadata)

  linearize = createIntentOption(documentOptimizeCommandFields.linearize)

  compatibility = createIntentOption(documentOptimizeCommandFields.compatibility)
}

class DocumentAutoRotateCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['document', 'auto-rotate']]

  static override intentDefinition = documentAutoRotateCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Auto-rotate documents to the correct orientation',
    details: 'Runs `/document/autorotate` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit document auto-rotate --input input.pdf --out output.pdf'],
    ],
  })
}

class DocumentThumbsCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['document', 'thumbs']]

  static override intentDefinition = documentThumbsCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Extract thumbnail images from documents',
    details: 'Runs `/document/thumbs` on each input file and writes the results to `--out`.',
    examples: [['Run the command', 'transloadit document thumbs --input input.pdf --out output/']],
  })

  page = createIntentOption(documentThumbsCommandFields.page)

  format = createIntentOption(documentThumbsCommandFields.format)

  delay = createIntentOption(documentThumbsCommandFields.delay)

  width = createIntentOption(documentThumbsCommandFields.width)

  height = createIntentOption(documentThumbsCommandFields.height)

  resizeStrategy = createIntentOption(documentThumbsCommandFields.resizeStrategy)

  background = createIntentOption(documentThumbsCommandFields.background)

  alpha = createIntentOption(documentThumbsCommandFields.alpha)

  density = createIntentOption(documentThumbsCommandFields.density)

  antialiasing = createIntentOption(documentThumbsCommandFields.antialiasing)

  colorspace = createIntentOption(documentThumbsCommandFields.colorspace)

  trimWhitespace = createIntentOption(documentThumbsCommandFields.trimWhitespace)

  pdfUseCropbox = createIntentOption(documentThumbsCommandFields.pdfUseCropbox)

  turbo = createIntentOption(documentThumbsCommandFields.turbo)
}

class AudioWaveformCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['audio', 'waveform']]

  static override intentDefinition = audioWaveformCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Generate waveform images from audio',
    details: 'Runs `/audio/waveform` on each input file and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit audio waveform --input input.mp3 --out output.png'],
    ],
  })

  ffmpeg = createIntentOption(audioWaveformCommandFields.ffmpeg)

  format = createIntentOption(audioWaveformCommandFields.format)

  width = createIntentOption(audioWaveformCommandFields.width)

  height = createIntentOption(audioWaveformCommandFields.height)

  antialiasing = createIntentOption(audioWaveformCommandFields.antialiasing)

  backgroundColor = createIntentOption(audioWaveformCommandFields.backgroundColor)

  centerColor = createIntentOption(audioWaveformCommandFields.centerColor)

  outerColor = createIntentOption(audioWaveformCommandFields.outerColor)

  style = createIntentOption(audioWaveformCommandFields.style)

  splitChannels = createIntentOption(audioWaveformCommandFields.splitChannels)

  zoom = createIntentOption(audioWaveformCommandFields.zoom)

  pixelsPerSecond = createIntentOption(audioWaveformCommandFields.pixelsPerSecond)

  bits = createIntentOption(audioWaveformCommandFields.bits)

  start = createIntentOption(audioWaveformCommandFields.start)

  end = createIntentOption(audioWaveformCommandFields.end)

  colors = createIntentOption(audioWaveformCommandFields.colors)

  borderColor = createIntentOption(audioWaveformCommandFields.borderColor)

  waveformStyle = createIntentOption(audioWaveformCommandFields.waveformStyle)

  barWidth = createIntentOption(audioWaveformCommandFields.barWidth)

  barGap = createIntentOption(audioWaveformCommandFields.barGap)

  barStyle = createIntentOption(audioWaveformCommandFields.barStyle)

  axisLabelColor = createIntentOption(audioWaveformCommandFields.axisLabelColor)

  noAxisLabels = createIntentOption(audioWaveformCommandFields.noAxisLabels)

  withAxisLabels = createIntentOption(audioWaveformCommandFields.withAxisLabels)

  amplitudeScale = createIntentOption(audioWaveformCommandFields.amplitudeScale)

  compression = createIntentOption(audioWaveformCommandFields.compression)
}

class TextSpeakCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['text', 'speak']]

  static override intentDefinition = textSpeakCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Speak text',
    details: 'Runs `/text/speak` on each input file and writes the result to `--out`.',
    examples: [
      [
        'Run the command',
        'transloadit text speak --input input.pdf --provider aws --out output.mp3',
      ],
    ],
  })

  prompt = createIntentOption(textSpeakCommandFields.prompt)

  provider = createIntentOption(textSpeakCommandFields.provider)

  targetLanguage = createIntentOption(textSpeakCommandFields.targetLanguage)

  voice = createIntentOption(textSpeakCommandFields.voice)

  ssml = createIntentOption(textSpeakCommandFields.ssml)
}

class VideoThumbsCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['video', 'thumbs']]

  static override intentDefinition = videoThumbsCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Extract thumbnails from videos',
    details: 'Runs `/video/thumbs` on each input file and writes the results to `--out`.',
    examples: [['Run the command', 'transloadit video thumbs --input input.mp4 --out output/']],
  })

  ffmpeg = createIntentOption(videoThumbsCommandFields.ffmpeg)

  count = createIntentOption(videoThumbsCommandFields.count)

  offsets = createIntentOption(videoThumbsCommandFields.offsets)

  format = createIntentOption(videoThumbsCommandFields.format)

  width = createIntentOption(videoThumbsCommandFields.width)

  height = createIntentOption(videoThumbsCommandFields.height)

  resizeStrategy = createIntentOption(videoThumbsCommandFields.resizeStrategy)

  background = createIntentOption(videoThumbsCommandFields.background)

  rotate = createIntentOption(videoThumbsCommandFields.rotate)

  inputCodec = createIntentOption(videoThumbsCommandFields.inputCodec)
}

class VideoEncodeHlsCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['video', 'encode-hls']]

  static override intentDefinition = videoEncodeHlsCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Run builtin/encode-hls-video@latest',
    details:
      'Runs the `builtin/encode-hls-video@latest` template and writes the outputs to `--out`.',
    examples: [['Run the command', 'transloadit video encode-hls --input input.mp4 --out output/']],
  })
}

class FileCompressCommand extends GeneratedBundledFileIntentCommand {
  static override paths = [['file', 'compress']]

  static override intentDefinition = fileCompressCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Compress files',
    details: 'Runs `/file/compress` for the provided inputs and writes the result to `--out`.',
    examples: [
      ['Run the command', 'transloadit file compress --input input.file --out archive.zip'],
    ],
  })

  format = createIntentOption(fileCompressCommandFields.format)

  gzip = createIntentOption(fileCompressCommandFields.gzip)

  password = createIntentOption(fileCompressCommandFields.password)

  compressionLevel = createIntentOption(fileCompressCommandFields.compressionLevel)

  fileLayout = createIntentOption(fileCompressCommandFields.fileLayout)

  archiveName = createIntentOption(fileCompressCommandFields.archiveName)
}

class FileDecompressCommand extends GeneratedStandardFileIntentCommand {
  static override paths = [['file', 'decompress']]

  static override intentDefinition = fileDecompressCommandDefinition

  static override usage = Command.Usage({
    category: 'Intent Commands',
    description: 'Decompress archives',
    details: 'Runs `/file/decompress` on each input file and writes the results to `--out`.',
    examples: [['Run the command', 'transloadit file decompress --input input.file --out output/']],
  })
}

export const intentCommands = [
  ImageGenerateCommand,
  PreviewGenerateCommand,
  ImageRemoveBackgroundCommand,
  ImageOptimizeCommand,
  ImageResizeCommand,
  DocumentConvertCommand,
  DocumentOptimizeCommand,
  DocumentAutoRotateCommand,
  DocumentThumbsCommand,
  AudioWaveformCommand,
  TextSpeakCommand,
  VideoThumbsCommand,
  VideoEncodeHlsCommand,
  FileCompressCommand,
  FileDecompressCommand,
] as const
