// Generated by CoffeeScript 1.7.1
(function() {
  var TransloaditClient, crypto, fs, reqr, request, _;

  reqr = global.GENTLY ? GENTLY.hijack(require) : require;

  request = reqr("request");

  crypto = reqr("crypto");

  _ = reqr("underscore");

  fs = reqr("fs");

  TransloaditClient = (function() {
    function TransloaditClient(opts) {
      opts = opts || {};
      this._authKey = opts.authKey || null;
      this._authSecret = opts.authSecret || null;
      this._service = opts.service || "api2.transloadit.com";
      this._region = opts.region || "us-east-1";
      this._protocol = "http://";
      this._streams = {};
    }

    TransloaditClient.prototype.addStream = function(name, stream) {
      stream.pause();
      return this._streams[name] = stream;
    };

    TransloaditClient.prototype.addFile = function(name, path) {
      var stream;
      stream = fs.createReadStream(path);
      return this.addStream(name, stream);
    };

    TransloaditClient.prototype.createAssembly = function(opts, cb) {
      return this._getBoredInstance(null, true, (function(_this) {
        return function(err, url) {
          var requestOpts;
          if (err || (url == null)) {
            return cb(err);
          }
          requestOpts = {
            url: "http://api2." + url + "/assemblies",
            method: "post",
            timeout: 24 * 60 * 60 * 1000,
            params: opts.params || {},
            fields: opts.fields || {}
          };
          return _this._remoteJson(requestOpts, function(err, result) {
            _this._streams = {};
            if (err) {
              return cb(err);
            }
            if (result && result.ok) {
              return cb(null, result);
            }
            err = new Error(result.error || "NOT OK");
            return cb(err);
          });
        };
      })(this));
    };

    TransloaditClient.prototype.deleteAssembly = function(assemblyId, cb) {
      var opts;
      opts = {
        url: this._serviceUrl() + ("/assemblies/" + assemblyId),
        timeout: 16000
      };
      return this._remoteJson(opts, function(err, result) {
        if (err) {
          return cb(err);
        }
        opts = {
          url: result.assembly_url,
          timeout: 5000
        };
        return request.del(opts, cb);
      });
    };

    TransloaditClient.prototype.replayAssembly = function(opts, cb) {
      var assemblyId, requestOpts;
      assemblyId = opts.assembly_id;
      requestOpts = {
        url: this._serviceUrl() + ("/assemblies/" + assemblyId + "/replay"),
        timeout: 5000,
        method: "post"
      };
      if (opts.notify_url != null) {
        requestOpts.params = {
          notify_url: opts.notify_url
        };
      }
      return this._remoteJson(requestOpts, cb);
    };

    TransloaditClient.prototype.replayAssemblyNotification = function(opts, cb) {
      var assemblyId, requestOpts;
      assemblyId = opts.assembly_id;
      requestOpts = {
        url: this._serviceUrl() + ("/assembly_notifications/" + assemblyId + "/replay"),
        timeout: 5000,
        method: "post"
      };
      if (opts.notify_url != null) {
        requestOpts.params = {
          notify_url: opts.notify_url
        };
      }
      return this._remoteJson(requestOpts, cb);
    };

    TransloaditClient.prototype.listAssemblyNotifications = function(params, cb) {
      var requestOpts;
      requestOpts = {
        url: this._serviceUrl() + "/assembly_notifications",
        timeout: 5000,
        method: "get",
        params: params || {}
      };
      return this._remoteJson(requestOpts, cb);
    };

    TransloaditClient.prototype.listAssemblies = function(params, cb) {
      var requestOpts;
      requestOpts = {
        url: this._serviceUrl() + "/assemblies",
        timeout: 5000,
        method: "get",
        params: params || {}
      };
      return this._remoteJson(requestOpts, cb);
    };

    TransloaditClient.prototype.assemblyStatus = function(assemblyId, cb) {
      var opts;
      opts = {
        url: this._serviceUrl() + ("/assemblies/" + assemblyId),
        timeout: 5000
      };
      return this._remoteJson(opts, (function(_this) {
        return function(err, result) {
          var status;
          if (err) {
            return cb(err);
          }
          status = result;
          opts = {
            url: result.assembly_url,
            timeout: 5000
          };
          return _this._remoteJson(opts, function(err, result) {
            if (err) {
              return cb(null, status);
            }
            return cb(null, result);
          });
        };
      })(this));
    };

    TransloaditClient.prototype.calcSignature = function(toSign) {
      return crypto.createHmac("sha1", this._authSecret).update(new Buffer(toSign, "utf-8")).digest("hex");
    };

    TransloaditClient.prototype._appendForm = function(req, params, fields) {
      var form, jsonParams, key, signature, val;
      jsonParams = this._prepareParams(params);
      signature = this.calcSignature(jsonParams);
      form = req.form();
      form.append("params", jsonParams);
      if (fields == null) {
        fields = [];
      }
      for (key in fields) {
        val = fields[key];
        if (_.isObject(fields[key]) || _.isArray(fields[key])) {
          val = JSON.stringify(fields[key]);
        }
        form.append(key, val);
      }
      form.append("signature", signature);
      return _.each(this._streams, function(value, key) {
        return form.append(key, value);
      });
    };

    TransloaditClient.prototype._appendParamsToUrl = function(url, params) {
      var jsonParams, signature;
      jsonParams = this._prepareParams(params);
      signature = this.calcSignature(jsonParams);
      if (url.indexOf("?") === -1) {
        url += "?signature=" + signature;
      } else {
        url += "&signature=" + signature;
      }
      jsonParams = encodeURIComponent(jsonParams);
      url += "&params=" + jsonParams;
      return url;
    };

    TransloaditClient.prototype._getBoredInstance = function(url, customBoredLogic, cb) {
      var opts;
      if (url === null) {
        url = this._serviceUrl() + "/instances/bored";
      }
      opts = {
        url: url,
        timeout: 5000
      };
      return this._remoteJson(opts, (function(_this) {
        return function(err, instance) {
          if (!err) {
            if (instance.error) {
              return cb(instance.error);
            }
            return cb(null, instance.api2_host);
          }
          if (customBoredLogic) {
            _this._findBoredInstanceUrl(function(err, theUrl) {
              if (err) {
                err = {
                  error: "BORED_INSTANCE_ERROR",
                  message: "Could not find a bored instance. " + err.message
                };
                return cb(err);
              }
              url = "" + _this._protocol + "api2." + theUrl + "/instances/bored";
              return _this._getBoredInstance(url, false, cb);
            });
            return;
          }
          err = {
            error: "CONNECTION_ERROR",
            message: "There was a problem connecting to the upload server",
            reason: err.message,
            url: url
          };
          return cb(err);
        };
      })(this));
    };

    TransloaditClient.prototype._findBoredInstanceUrl = function(cb) {
      var opts, url;
      url = "http://infra-" + this._region + ".transloadit.com.s3.amazonaws.com/";
      url += "cached_instances.json";
      opts = {
        url: url,
        timeout: 3000
      };
      return this._remoteJson(opts, (function(_this) {
        return function(err, result) {
          var instances;
          if (err) {
            err.message = "Could not query S3 for cached uploaders: " + err.message;
            return cb(err);
          }
          instances = _.shuffle(result.uploaders);
          return _this._findResponsiveInstance(instances, 0, cb);
        };
      })(this));
    };

    TransloaditClient.prototype._findResponsiveInstance = function(instances, index, cb) {
      var err, opts, url;
      if (!instances[index]) {
        err = new Error("No responsive uploaders");
        return cb(err);
      }
      url = this._protocol + instances[index];
      opts = {
        url: url,
        timeout: 3000
      };
      return this._remoteJson(opts, (function(_this) {
        return function(err, result) {
          if (err) {
            return _this._findResponsiveInstance(instances, index + 1, cb);
          }
          return cb(null, url);
        };
      })(this));
    };

    TransloaditClient.prototype._prepareParams = function(params) {
      if (params == null) {
        params = {};
      }
      if (params.auth == null) {
        params.auth = {};
      }
      if (params.auth.key == null) {
        params.auth.key = this._authKey;
      }
      params.auth.expires = this._getExpiresDate();
      return JSON.stringify(params);
    };

    TransloaditClient.prototype._getExpiresDate = function() {
      var expiresDate;
      expiresDate = new Date();
      expiresDate.setDate(expiresDate.getDate() + 1);
      return expiresDate.toISOString();
    };

    TransloaditClient.prototype._serviceUrl = function() {
      return this._protocol + this._service;
    };

    TransloaditClient.prototype._remoteJson = function(opts, cb) {
      var err, method, req, requestOpts, timeout, url;
      timeout = opts.timeout || 5000;
      url = opts.url || null;
      method = opts.method || "get";
      if (!url) {
        err = new Error("No url provided!");
        return cb(err);
      }
      if (method === "get" && (opts.params != null)) {
        url = this._appendParamsToUrl(url, opts.params);
      }
      requestOpts = {
        uri: url,
        timeout: timeout
      };
      req = request[method](requestOpts, function(err, res) {
        var e, result;
        if (err) {
          return cb(err);
        }
        result = null;
        try {
          result = JSON.parse(res.body);
        } catch (_error) {
          e = _error;
          return cb(e);
        }
        return cb(null, result);
      });
      if (method === "post") {
        return this._appendForm(req, opts.params, opts.fields);
      }
    };

    return TransloaditClient;

  })();

  module.exports = TransloaditClient;

}).call(this);
