name: Tests

on:
  push:
    branches:
      - master
      - slack-test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      # Integration tests are not yet ready to run in parallel
      max-parallel: 1
      matrix:
        node: ['10', '12', '14']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn
      - run: npm run lint

  slack-on-failure:
    needs: [test]
    if: always()
#    if: failure()

    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
