name: Pull request temporary tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: yarn

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - run: |
          curl https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 --output cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
      - run: npm run test-integration
        env:
          TRANSLOADIT_KEY: ${{ secrets.TRANSLOADIT_KEY }}
          TRANSLOADIT_SECRET: ${{ secrets.TRANSLOADIT_SECRET }}
          CLOUDFLARED_PATH: ./cloudflared-linux-amd64
